#!/usr/bin/python
import os
import subprocess
import sys

POSTFLIGHT_SCRIPT = "/usr/local/munki/postflight"
POSTFLIGHT_DIR = "/usr/local/munki/postflight.d"

ZENTRAL_PFD_SCRIPT = "/usr/local/zentral/munki/postflight"
ZENTRAL_PF_SCRIPT = "/usr/local/zentral/munki/zentral_postflight"

# prepare postflight.d dir and save existing postflight script
if not os.path.isdir(POSTFLIGHT_DIR):
    os.makedirs(POSTFLIGHT_DIR)
    if os.path.isfile(POSTFLIGHT_SCRIPT):
        os.rename(POSTFLIGHT_SCRIPT, os.path.join(POSTFLIGHT_DIR, "postflight.bckp"))
    os.symlink(ZENTRAL_PFD_SCRIPT, POSTFLIGHT_SCRIPT)

# install zentral postflight script
zentral_pf_script_install_path = os.path.join(POSTFLIGHT_DIR, "zentral")
if os.path.exists(zentral_pf_script_install_path):
    os.unlink(zentral_pf_script_install_path)
os.symlink(ZENTRAL_PF_SCRIPT, zentral_pf_script_install_path)

# call the postflight to send fresh and complete infos to zentral
if subprocess.call([ZENTRAL_PF_SCRIPT, "auto"]):
    print "Error running the Zentral postflight script"
    sys.exit(1)

# write zentral base url
if subprocess.call(["defaults", "write",
                    "/Library/Preferences/io.zentral.plist",
                    "base_url", "https://%TLS_HOSTNAME%"]):
    print "Could not write the io.zentral.plist"
    sys.exit(1)
