title: Keyboard Settings
description: The declaration to configure keyboard settings.
payload:
  declarationtype: com.apple.configuration.keyboard.settings
  supportedOS:
    iOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
      sharedipad:
        allowed-scopes:
        - user
    macOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
      - user
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  apply: combined
payloadkeys:
- key: AllowAutoCorrection
  title: Allow auto-correction
  supportedOS:
    macOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables auto-correction.
- key: AllowDefinitionLookup
  title: Allow definition lookup
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables definition lookup.
- key: AllowDictation
  title: Allow dictation
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables dictation.
- key: AllowMathKeyboardSuggestions
  title: Allow math keyboard suggestions
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables keyboard suggestions that include math solutions.
    This key is also supported by the math.settings configuration.
- key: AllowPredictiveText
  title: Allow predictive text
  supportedOS:
    macOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables predictive text.
- key: AllowSlideToType
  title: Allow slide to type
  supportedOS:
    macOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables slide to type.
- key: AllowSpellCheck
  title: Allow spell check
  supportedOS:
    macOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables spell check.
- key: AllowTextReplacement
  title: Allow text replacement
  supportedOS:
    macOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables text replacement.
examples:
  title: Configuration examples
  files:
  - tab: Keyboard Restrictions
    description: This configuration restricts keyboard features.
    file: examples/declarative/declarations/configurations/keyboard.settings/example1.json
