title: Siri Settings
description: The declaration to configure Siri settings.
payload:
  declarationtype: com.apple.configuration.siri.settings
  supportedOS:
    iOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
      sharedipad:
        allowed-scopes:
        - user
    macOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
      - user
    tvOS:
      introduced: '27.0'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
    visionOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
    watchOS:
      introduced: '26.4'
      allowed-enrollments:
      - supervised
      allowed-scopes:
      - system
  apply: combined
payloadkeys:
- key: Enabled
  title: Enabled
  supportedOS:
    watchOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables Siri.
- key: AllowUserGeneratedContent
  title: Allow user generated content
  supportedOS:
    macOS:
      introduced: n/a
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables Siri user-generated content.
- key: AllowWhileLocked
  title: Allow while locked
  supportedOS:
    macOS:
      introduced: n/a
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: true
  combinetype: boolean-and
  content: If `false`, disables Siri while locked.
- key: ForceProfanityFilter
  title: Force profanity filter
  supportedOS:
    tvOS:
      introduced: n/a
    visionOS:
      introduced: n/a
    watchOS:
      introduced: n/a
  type: <boolean>
  presence: optional
  default: false
  combinetype: boolean-or
  content: If `true`, forces Siri profanity filter.
examples:
  title: Configuration examples
  files:
  - tab: Siri Restrictions
    description: This configuration restricts Siri features.
    file: examples/declarative/declarations/configurations/siri.settings/example1.json
