# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import zentral.contrib.nagios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0020_machinesnapshotcommit_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagiosInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(editable=False)),
                ('url', models.URLField(unique=True)),
                ('secret', models.CharField(default=zentral.contrib.nagios.models.make_secret,
                                            editable=False, max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(blank=True, null=True,
                                                    on_delete=django.db.models.deletion.PROTECT,
                                                    to='inventory.BusinessUnit')),
            ],
        ),
    ]
