# Generated by Django 5.2.14 on 2026-06-24 15:01

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("compliance_checks", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0083_delete_metabusinessunittag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "collect_inventory",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, the agent posts a full machine inventory snapshot "
                        "on the interval below",
                    ),
                ),
                (
                    "inventory_interval",
                    models.IntegerField(
                        default=86400,
                        help_text="Inventory refresh interval in seconds (Minimum: 60s)",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(604800),
                        ],
                    ),
                ),
                (
                    "default_check_interval",
                    models.IntegerField(
                        default=86400,
                        help_text="Default run interval in seconds for recurring jobs that don't set their own",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(604800),
                        ],
                    ),
                ),
                (
                    "config_refresh_interval",
                    models.IntegerField(
                        default=600,
                        help_text="How long the agent may trust a cached configuration before refreshing "
                        "it, in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(604800),
                        ],
                    ),
                ),
                (
                    "results_batch_size",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of results the agent uploads per request; a larger backlog "
                        "is drained over several requests",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("script", "Script"), ("mscp_check", "mSCP check")], editable=False, max_length=32
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveSmallIntegerField(default=1, editable=False)),
                ("distributor_pk", models.PositiveIntegerField(editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuration",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="turbo.configuration"),
                ),
                (
                    "distributor_content_type",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "secret",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s",
                        to="inventory.enrollmentsecret",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("distributor_content_type", "distributor_pk")},
            },
        ),
        migrations.CreateModel(
            name="OneTimeJob",
            fields=[
                (
                    "serial_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "excluded_serial_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("not_after", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuration",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.configuration"),
                ),
                (
                    "excluded_tags",
                    models.ManyToManyField(
                        blank=True, related_name="%(app_label)s_%(class)s_excluded_tags", to="inventory.tag"
                    ),
                ),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.job")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="%(app_label)s_%(class)s_tags", to="inventory.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MachineJobStatus",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("serial_number", models.TextField(db_index=True)),
                ("seen_version", models.PositiveIntegerField(null=True)),
                ("seen_interval", models.PositiveIntegerField(null=True)),
                ("result_version", models.PositiveIntegerField(null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(null=True)),
                ("first_result_at", models.DateTimeField(null=True)),
                ("last_result_at", models.DateTimeField(null=True)),
                ("removed_at", models.DateTimeField(null=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.job")),
                (
                    "one_time_job",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="turbo.onetimejob"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringJob",
            fields=[
                (
                    "serial_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "excluded_serial_numbers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "interval",
                    models.IntegerField(
                        blank=True,
                        help_text="Run interval in seconds; leave empty to use the configuration default",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(60),
                            django.core.validators.MaxValueValidator(604800),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configuration",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.configuration"),
                ),
                (
                    "excluded_tags",
                    models.ManyToManyField(
                        blank=True, related_name="%(app_label)s_%(class)s_excluded_tags", to="inventory.tag"
                    ),
                ),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.job")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="%(app_label)s_%(class)s_tags", to="inventory.tag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "source",
                    models.TextField(help_text="zsh script; exit 0 = OK, exit > 0 = FAIL"),
                ),
                ("arch_amd64", models.BooleanField(default=True, verbose_name="Run on Intel architecture")),
                ("arch_arm64", models.BooleanField(default=True, verbose_name="Run on Apple Silicon architecture")),
                ("min_os_version", models.CharField(blank=True, max_length=32)),
                ("max_os_version", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_check",
                    models.OneToOneField(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turbo_script",
                        to="compliance_checks.compliancecheck",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script",
                        to="turbo.job",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Added on exit 0, removed on exit > 0",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrolledMachine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("serial_number", models.TextField(db_index=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("last_seen_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="turbo.enrollment")),
            ],
            options={
                "unique_together": {("enrollment", "serial_number")},
            },
        ),
        migrations.CreateModel(
            name="MSCPCheck",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("rule_id", models.TextField()),
                (
                    "baseline",
                    models.CharField(
                        blank=True,
                        help_text="mSCP baseline key (e.g. cis_lvl1, stig); the agent uses that baseline's "
                        "default ODV for the rule. Mutually exclusive with an explicit ODV override below.",
                        max_length=64,
                    ),
                ),
                ("odv_int", models.IntegerField(blank=True, null=True)),
                ("odv_string", models.TextField(blank=True, null=True)),
                ("odv_bool", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "compliance_check",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turbo_mscp_check",
                        to="compliance_checks.compliancecheck",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mscp_check",
                        to="turbo.job",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("odv_int__isnull", True), ("odv_string__isnull", True)),
                            models.Q(("odv_bool__isnull", True), ("odv_int__isnull", True)),
                            models.Q(("odv_bool__isnull", True), ("odv_string__isnull", True)),
                            _connector="OR",
                        ),
                        name="turbo_mscpcheck_at_most_one_odv",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("baseline", ""),
                            models.Q(
                                ("odv_bool__isnull", True), ("odv_int__isnull", True), ("odv_string__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="turbo_mscpcheck_baseline_xor_odv",
                    ),
                    models.UniqueConstraint(
                        fields=("rule_id", "baseline", "odv_int", "odv_string", "odv_bool"),
                        name="turbo_mscpcheck_unique_rule_baseline_odv",
                        nulls_distinct=False,
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="onetimejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("not_before__isnull", True),
                    ("not_after__isnull", True),
                    ("not_before__lte", models.F("not_after")),
                    _connector="OR",
                ),
                name="turbo_onetimejob_not_before_lte_not_after",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinejobstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("one_time_job__isnull", True)),
                fields=("serial_number", "job"),
                name="turbo_mjs_unique_recurring",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinejobstatus",
            constraint=models.UniqueConstraint(
                condition=models.Q(("one_time_job__isnull", False)),
                fields=("serial_number", "one_time_job"),
                name="turbo_mjs_unique_onetime",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringjob",
            constraint=models.UniqueConstraint(
                fields=("configuration", "job"), name="turbo_recurringjob_unique_config_job"
            ),
        ),
    ]
