# Generated by Django 5.2.17 on 2026-09-03 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbo', '0002_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True,
                                        serialize=False)),
                ('schedule_pk', models.UUIDField()),
                ('schedule_mode', models.CharField(
                    choices=[('recurring', 'Recurring'), ('one_time', 'One-time')], max_length=32)),
                ('serial_number', models.TextField(db_index=True)),
                ('run_id', models.UUIDField()),
                ('artifact', models.CharField(max_length=64)),
                ('key', models.TextField()),
                ('mode', models.CharField(
                    choices=[('put', 'Single PUT'), ('multipart', 'Multipart')],
                    default='put', max_length=32)),
                ('part_size', models.PositiveIntegerField(null=True)),
                ('upload_id', models.TextField(null=True)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('crc64nvme', models.CharField(blank=True, max_length=32)),
                ('crc32c', models.CharField(blank=True, max_length=32)),
                ('truncated', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('failed', 'Failed')],
                    default='pending', max_length=32)),
                ('error_reason', models.CharField(
                    choices=[('expired', 'URL expired'), ('http_status', 'HTTP status'),
                             ('network', 'Network'), ('too_large', 'Too large'),
                             ('mint_rejected', 'Mint rejected')],
                    max_length=32, null=True)),
                ('verification', models.CharField(
                    choices=[('pending', 'Pending'), ('verified', 'Verified'), ('mismatch', 'Mismatch'),
                             ('missing', 'Missing'), ('assembly_failed', 'Assembly failed')],
                    default='pending', max_length=32)),
                ('verified_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'default_permissions': (),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('schedule_pk', 'serial_number', 'run_id', 'artifact'),
                        name='turbo_jobupload_unique_run_artifact'),
                ],
            },
        ),
    ]
