sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

install:
  - docker-compose pull
  - docker-compose build
  - docker-compose up -d db rabbitmq elastic

script: docker-compose run --rm web tests
