# Generated by Django 2.2.17 on 2020-11-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_machine_snapshot_certificates_on_delete_cascade'),
        ('jamf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('GROUP', 'Group')], default='GROUP', max_length=16)),
                ('regex', models.CharField(
                     help_text='matching names will be used to automatically generate tags',
                     max_length=256
                 )),
                ('replacement', models.CharField(
                     help_text='replacement pattern used to generate a tag name from a tag regex match',
                     max_length=32
                 )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamf.JamfInstance')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Taxonomy')),
            ],
        ),
    ]
