# Generated by Django 2.2.18 on 2021-03-17 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf', '0002_tagconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamfinstance',
            name='inventory_apps_shard',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
