# Generated by Django 2.2.27 on 2022-03-16 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf', '0004_auto_20211008_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamfinstance',
            name='checkin_heartbeat_timeout',
            field=models.IntegerField(default=1200, help_text='in seconds, 600 (10 min) → 172800 (2 days)',
                                      validators=[django.core.validators.MinValueValidator(600),
                                                  django.core.validators.MaxValueValidator(172800)]),
        ),
        migrations.AddField(
            model_name='jamfinstance',
            name='inventory_completed_heartbeat_timeout',
            field=models.IntegerField(default=172800, help_text='in seconds, 600 (10 min) → 604800 (7 days)',
                                      validators=[django.core.validators.MinValueValidator(600),
                                                  django.core.validators.MaxValueValidator(604800)]),
        ),
    ]
