# Generated by Django 2.2.27 on 2022-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf', '0005_auto_20220316_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamfinstance',
            name='bearer_token_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
