# Generated by Django 3.2.14 on 2022-10-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamf', '0007_jamfinstance_inventory_extension_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamfinstance',
            name='principal_user_dn_extension_attribute',
            field=models.CharField(
                blank=True,
                help_text='Extension attribute to use as principal user display name', max_length=256, null=True,
                verbose_name='Principal user display name extension attribute'),
        ),
        migrations.AddField(
            model_name='jamfinstance',
            name='principal_user_pn_extension_attribute',
            field=models.CharField(
                blank=True,
                help_text='Extension attribute to use as principal user principal name', max_length=256, null=True,
                verbose_name='Principal user principal name extension attribute'),
        ),
        migrations.AddField(
            model_name='jamfinstance',
            name='principal_user_uid_extension_attribute',
            field=models.CharField(
                blank=True,
                help_text='Extension attribute to use as principal user unique ID', max_length=256, null=True,
                verbose_name='Principal user UID extension attribute'),
        ),
    ]
