# Generated by Django 4.2.23 on 2025-07-15 13:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("name", models.CharField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("backend_kwargs", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provisioning_uid",
                    models.CharField(
                        editable=False, max_length=256, null=True, unique=True
                    ),
                ),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "admin_console",
                    models.BooleanField(
                        default=False, verbose_name="Use for admin console"
                    ),
                ),
                ("event_filters", models.JSONField(default=dict)),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("DATADOG", "Datadog"),
                            ("ELASTICSEARCH", "Elasticsearch"),
                            ("HTTP", "HTTP"),
                            ("KINESIS", "Kinesis"),
                            ("OPENSEARCH", "OpenSearch"),
                            ("PANTHER", "Panther"),
                            ("SNOWFLAKE", "Snowflake"),
                            ("SPLUNK", "Splunk"),
                            ("SUMO_LOGIC", "Sumo Logic"),
                        ]
                    ),
                ),
                (
                    "events_url_authorized_roles",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
