# Generated by Django 5.2.9 on 2025-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="backend",
            field=models.CharField(
                choices=[
                    ("CLICKHOUSE", "ClickHouse"),
                    ("DATADOG", "Datadog"),
                    ("ELASTICSEARCH", "Elasticsearch"),
                    ("HTTP", "HTTP"),
                    ("KINESIS", "Kinesis"),
                    ("OPENSEARCH", "OpenSearch"),
                    ("PANTHER", "Panther"),
                    ("S3_PARQUET", "S3 Parquet"),
                    ("SNOWFLAKE", "Snowflake"),
                    ("SPLUNK", "Splunk"),
                    ("SUMO_LOGIC", "Sumo Logic"),
                ]
            ),
        ),
    ]
