# Generated by Django 5.2.9 on 2025-12-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='customer_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='type',
            field=models.CharField(choices=[('OAUTH', 'OAuth Admin SDK'), ('SA_CLOUD_ID', 'Service Account Could Identity')], default='OAUTH'),
        ),
    ]
