# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0020_machinesnapshotcommit_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMDMApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplemdm_id', models.IntegerField(verbose_name='SimpleMDM ID')),
                ('builder', models.CharField(max_length=256)),
                ('build_kwargs', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Builder parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleMDMInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('account_name', models.TextField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.BusinessUnit')),
            ],
        ),
        migrations.AddField(
            model_name='simplemdmapp',
            name='simplemdm_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplemdm.SimpleMDMInstance'),
        ),
    ]
