# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplemdm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplemdmapp',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
