# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplemdm', '0002_simplemdmapp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplemdmapp',
            name='build_kwargs',
        ),
        migrations.AddField(
            model_name='simplemdmapp',
            name='enrollment_pk',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
