# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 17:49
from __future__ import unicode_literals

from django.db import migrations, models
from zentral.contrib.inventory.models import BusinessUnit, MachineGroup


def make_keys(apps, schema_editor):
    for b in BusinessUnit.objects.all():
        b.save()
    for g in MachineGroup.objects.all():
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessunit',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='machinegroup',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.RunPython(make_keys),
        migrations.AlterField(
            model_name='businessunit',
            name='key',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='key',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
