# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineTagManager',
        ),
        migrations.DeleteModel(
            name='TagManager',
        ),
        migrations.AlterField(
            model_name='machinetag',
            name='serial_number',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='machinetag',
            unique_together=set([('serial_number', 'tag')]),
        ),
    ]
