# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20151222_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='sha1',
            new_name='sha_1',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='sha256',
            new_name='sha_256',
        ),
        migrations.RenameField(
            model_name='osxapp',
            old_name='version',
            new_name='bundle_version',
        ),
        migrations.RenameField(
            model_name='osxapp',
            old_name='version_str',
            new_name='bundle_version_str',
        ),
        migrations.RenameField(
            model_name='osxappinstance',
            old_name='sha1',
            new_name='sha_1',
        ),
        migrations.RenameField(
            model_name='osxappinstance',
            old_name='sha256',
            new_name='sha_256',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='organizational_unit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
