# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20151222_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(max_length=40, unique=True)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('teamviewer_id', models.TextField()),
                ('release', models.TextField(blank=True, null=True)),
                ('unattended', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='teamviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.TeamViewer'),
        ),
    ]
