# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import zentral.contrib.inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160505_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='0079bf', max_length=6, validators=[zentral.contrib.inventory.models.validate_color]),
        ),
    ]
