# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20151223_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinegroup',
            name='machine_links',
            field=models.ManyToManyField(related_name='_machinegroup_machine_links_+', to='inventory.Link'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='links',
            field=models.ManyToManyField(related_name='_machinegroup_links_+', to='inventory.Link'),
        ),
    ]
