# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20160621_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshot',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
