# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_machinesnapshot_archived_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(db_index=True, max_length=40)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.TextField()),
                ('mac', models.CharField(max_length=17)),
                ('address', models.GenericIPAddressField(unpack_ipv4=True)),
                ('mask', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('broadcast', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='network_interfaces',
            field=models.ManyToManyField(to='inventory.NetworkInterface'),
        ),
    ]
