# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20161019_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshot',
            name='public_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
