# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_machinesnapshot_public_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MACAddressBlockAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', models.CharField(choices=[('MA-L', 'MA-L'), ('MA-M', 'MA-M'), ('MA-S', 'MA-S')], max_length=8)),
                ('assignment', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MACAddressBlockAssignmentOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='networkinterface',
            options={'ordering': ('interface',)},
        ),
        migrations.AlterUniqueTogether(
            name='macaddressblockassignmentorganization',
            unique_together=set([('name', 'address')]),
        ),
        migrations.AddField(
            model_name='macaddressblockassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MACAddressBlockAssignmentOrganization'),
        ),
    ]
