# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20161019_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshot',
            name='platform',
            field=models.CharField(blank=True, choices=[('LINUX', 'Linux'), ('MACOS', 'macOS'), ('WINDOWS', 'Windows'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='type',
            field=models.CharField(blank=True, choices=[('DESKTOP', 'Desktop'), ('LAPTOP', 'Laptop'), ('MOBILE', 'Mobile'), ('SERVER', 'Server'), ('TABLET', 'Tablet'), ('VM', 'VM')], max_length=32, null=True),
        ),
    ]
