# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20161202_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(db_index=True, max_length=40)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('source', models.TextField()),
                ('size', models.BigIntegerField()),
                ('arch', models.TextField()),
                ('revision', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='deb_packages',
            field=models.ManyToManyField(to='inventory.DebPackage'),
        ),
    ]
