# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20161212_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debpackage',
            name='arch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debpackage',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debpackage',
            name='revision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debpackage',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debpackage',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debpackage',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
