# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20161212_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesnapshot',
            name='mt_hash',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='machinesnapshot',
            unique_together=set([('mt_hash', 'mt_next')]),
        ),
    ]
