# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20161213_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshotcommit',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
