# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_machinesnapshotcommit_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='sha_1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
