# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20170608_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshotcommit',
            name='system_uptime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
