# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_machinesnapshotcommit_system_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osversion',
            name='minor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
