# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-15 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_enrollmentsecret_enrollmentsecretrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='serial_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='udids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
