# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20171015_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshot',
            name='imei',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='meid',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
