# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_enrollmentsecret_request_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.Tag'),
        ),
        migrations.AlterField(
            model_name='enrollmentsecretrequest',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentsecretrequest',
            name='udid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
