# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20171025_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentsecret',
            name='config',
        ),
        migrations.RemoveField(
            model_name='enrollmentsecret',
            name='module',
        ),
    ]
