# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-08 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20171107_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
