# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20171108_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesnapshot',
            name='reference',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
