# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_auto_20171120_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinesnapshotcommit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.MachineSnapshotCommit'),
        ),
    ]
