# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-04 10:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_auto_20180623_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabusinessunit',
            name='dashboard_osx_app_bundle_id_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
    ]
