# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20180918_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='meta_business_unit',
            field=models.ForeignKey(help_text='The business unit the machine will be assigned to at enrollment', on_delete=django.db.models.deletion.CASCADE, to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='The tags that the machine will get at enrollment', to='inventory.Tag'),
        ),
    ]
