# Generated by Django 2.1.7 on 2019-02-27 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_auto_20190227_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='request_count',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='enrollmentsecret',
            name='secret',
            field=models.CharField(editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
