# Generated by Django 2.1.7 on 2019-03-27 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_auto_20190227_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metabusinessunit',
            name='dashboard_osx_app_bundle_id_list',
        ),
        migrations.RemoveField(
            model_name='metabusinessunit',
            name='dashboard_source',
        ),
    ]
