# Generated by Django 2.2 on 2019-04-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_auto_20190327_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureADInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(max_length=40, unique=True)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('device_unique_id', models.TextField(blank=True, null=True)),
                ('local_user_name', models.TextField(blank=True, null=True)),
                ('user_unique_id', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='azure_ad_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.AzureADInfo'),
        ),
    ]
