# Generated by Django 2.2.3 on 2019-09-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0047_auto_20190930_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinesnapshot',
            name='azure_ad_info',
        ),
        migrations.DeleteModel(
            name='AzureADInfo',
        ),
    ]
