# Generated by Django 2.2.17 on 2020-12-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_machine_snapshot_certificates_on_delete_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalusersource',
            name='type',
            field=models.CharField(choices=[('COMPANY_PORTAL', 'Company portal'),
                                            ('GOOGLE_CHROME', 'Google Chrome')], max_length=64),
        ),
    ]
