# Generated by Django 2.2.17 on 2020-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_auto_20201201_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalusersource',
            name='type',
            field=models.CharField(choices=[('COMPANY_PORTAL', 'Company portal'),
                                            ('GOOGLE_CHROME', 'Google Chrome'),
                                            ('LOGGED_IN_USER', 'Logged-in user')], max_length=64),
        ),
    ]
