# Generated by Django 2.2.18 on 2021-03-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0052_auto_20210122_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='osxapp',
            name='bundle_display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
