# Generated by Django 2.2.18 on 2021-03-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_auto_20210317_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpackage',
            name='maintainer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debpackage',
            name='priority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debpackage',
            name='section',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debpackage',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
