# Generated by Django 2.2.24 on 2021-12-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_checks', '0001_initial'),
        ('inventory', '0060_auto_20211210_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='JMESPathCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('jmespath_expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compliance_check', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='jmespath_check',
                                                          to='compliance_checks.ComplianceCheck')),
                ('tags', models.ManyToManyField(blank=True, to='inventory.Tag')),
            ],
        ),
    ]
