# Generated by Django 2.2.24 on 2021-12-26 13:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0061_jmespathcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinesnapshot',
            name='extra_facts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
