# Generated by Django 2.2.27 on 2022-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0063_currentmachinesnapshot_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(max_length=40, unique=True)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.TextField()),
                ('version_name', models.TextField()),
                ('version_code', models.IntegerField(blank=True, null=True)),
                ('package_name', models.TextField(blank=True, null=True)),
                ('installer_package_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IOSApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt_hash', models.CharField(max_length=40, unique=True)),
                ('mt_created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('ad_hoc_signed', models.BooleanField(blank=True, null=True)),
                ('app_store_vendable', models.BooleanField(blank=True, null=True)),
                ('beta_app', models.BooleanField(blank=True, null=True)),
                ('bundle_size', models.BigIntegerField(blank=True, null=True)),
                ('device_based_vpp', models.BooleanField(blank=True, null=True)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('is_validated', models.BooleanField(blank=True, null=True)),
                ('short_version', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='principalusersource',
            name='type',
            field=models.CharField(choices=[('COMPANY_PORTAL', 'Company portal'),
                                            ('GOOGLE_CHROME', 'Google Chrome'),
                                            ('INVENTORY', 'Inventory'),
                                            ('LOGGED_IN_USER', 'Logged-in user'),
                                            ('SANTA_MACHINE_OWNER', 'Santa machine owner')], max_length=64),
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='android_apps',
            field=models.ManyToManyField(to='inventory.AndroidApp'),
        ),
        migrations.AddField(
            model_name='machinesnapshot',
            name='ios_apps',
            field=models.ManyToManyField(to='inventory.IOSApp'),
        ),
    ]
