# Generated by Django 3.2.13 on 2022-06-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0071_osversion_version'),
    ]

    operations = [
        # android apps
        migrations.RunSQL(
            "ALTER SEQUENCE inventory_machinesnapshot_android_apps_id_seq "
            "AS bigint MAXVALUE 9223372036854775807;"
        ),
        migrations.RunSQL(
            "ALTER TABLE inventory_machinesnapshot_android_apps "
            "ALTER COLUMN id TYPE bigint;"
        ),
        # deb packages
        migrations.RunSQL(
            "ALTER SEQUENCE inventory_machinesnapshot_deb_packages_id_seq "
            "AS bigint MAXVALUE 9223372036854775807;"
        ),
        migrations.RunSQL(
            "ALTER TABLE inventory_machinesnapshot_deb_packages "
            "ALTER COLUMN id TYPE bigint;"
        ),
        # iOS apps
        migrations.RunSQL(
            "ALTER SEQUENCE inventory_machinesnapshot_ios_apps_id_seq "
            "AS bigint MAXVALUE 9223372036854775807;"
        ),
        migrations.RunSQL(
            "ALTER TABLE inventory_machinesnapshot_ios_apps "
            "ALTER COLUMN id TYPE bigint;"
        ),
        # osx app instances
        migrations.RunSQL(
            "ALTER SEQUENCE inventory_machinesnapshot_osx_app_instances_id_seq "
            "AS bigint MAXVALUE 9223372036854775807;"
        ),
        migrations.RunSQL(
            "ALTER TABLE inventory_machinesnapshot_osx_app_instances "
            "ALTER COLUMN id TYPE bigint;"
        ),
        # program instances
        migrations.RunSQL(
            "ALTER SEQUENCE inventory_machinesnapshot_program_instances_id_seq "
            "AS bigint MAXVALUE 9223372036854775807;"
        ),
        migrations.RunSQL(
            "ALTER TABLE inventory_machinesnapshot_program_instances "
            "ALTER COLUMN id TYPE bigint;"
        ),
    ]
