# Generated by Django 3.2.13 on 2022-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0072_machinesnapshot_m2m_seq_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metabusinessunit',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
