# Generated by Django 3.2.14 on 2022-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0074_auto_20220919_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentmachinesnapshot',
            name='tree',
            field=models.JSONField(null=True),
        ),
    ]
