# Generated by Django 3.2.14 on 2023-01-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0075_currentmachinesnapshot_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentmachinesnapshot',
            name='tree',
        ),
    ]
