# Generated by Django 4.1.9 on 2023-06-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0076_remove_currentmachinesnapshot_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='signing_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
