# Generated by Django 4.2.13 on 2024-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_file_signing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cdhash',
            field=models.CharField(db_index=True, max_length=40, blank=True, null=True),
        ),
    ]
