# Generated by Django 4.2.26 on 2025-11-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0078_file_cdhash"),
    ]

    operations = [
        migrations.AddField(
            model_name="disk",
            name="encryption_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disk",
            name="filevault_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disk",
            name="label",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disk",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
