# Generated by Django 5.2.9 on 2025-12-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0079_disk_encryption_status_disk_filevault_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payload",
            name="uuid",
            field=models.TextField(blank=True, null=True),
        ),
    ]
