# Generated by Django 5.2.9 on 2026-01-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0080_alter_payload_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="upgrade_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
