# Generated by Django 5.2.11 on 2026-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0081_program_upgrade_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.CharField(editable=False, unique=True),
        ),
    ]
