# Generated by Django 5.2.9 on 2026-01-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0081_program_upgrade_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="package_family_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
