# Generated by Django 5.2.13 on 2026-04-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0082_alter_tag_name_alter_tag_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaBusinessUnitTag",
        ),
    ]
