# Generated by Django 5.2.16 on 2026-07-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0083_delete_metabusinessunittag'),
    ]

    operations = [
        migrations.AddField(
            model_name='osxappinstance',
            name='cd_hash',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='osxappinstance',
            name='entitlements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osxappinstance',
            name='secure_signing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osxappinstance',
            name='signing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='osxappinstance',
            name='team_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
