# Generated by Django 5.2.16 on 2026-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_osxappinstance_cd_hash_osxappinstance_entitlements_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currentmachinesnapshot',
            index=models.Index(fields=['last_seen'], name='inventory_cms_last_seen'),
        ),
    ]
