# Generated by Django 2.2.9 on 2020-02-25 19:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backend', models.CharField(editable=False, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
                ('enabled_for_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('claims', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.Realm')),
            ],
            options={
                'unique_together': {('realm', 'username')},
            },
        ),
        migrations.CreateModel(
            name='RealmAuthenticationSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('callback', models.CharField(max_length=255)),
                ('callback_kwargs', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='realms.Realm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.RealmUser')),
            ],
        ),
    ]
