# Generated by Django 2.2.9 on 2020-02-27 12:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmauthenticationsession',
            name='backend_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
