# Generated by Django 2.2.10 on 2020-03-05 21:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_realmauthenticationsession_backend_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmauthenticationsession',
            name='save_password_hash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realmuser',
            name='password_hash',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
