# Generated by Django 2.2.15 on 2020-11-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0004_auto_20201102_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='login_session_expiry',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
