# Generated by Django 2.2.18 on 2021-03-10 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('realms', '0005_realm_login_session_expiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealmGroupMapping',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realms.Realm')),
            ],
            options={
                'unique_together': {('realm', 'claim', 'value', 'group')},
            },
        ),
    ]
