# Generated by Django 3.2.12 on 2022-03-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_realmgroupmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realm',
            name='config',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='realmauthenticationsession',
            name='backend_state',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='realmauthenticationsession',
            name='callback_kwargs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='realmuser',
            name='claims',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='realmuser',
            name='password_hash',
            field=models.JSONField(null=True),
        ),
    ]
