# Generated by Django 4.1.9 on 2023-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0007_auto_20220329_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='realmgroupmapping',
            name='separator',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
