# Generated by Django 4.2.15 on 2024-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0010_realmgroup_alter_realmuser_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realm',
            name='user_portal',
            field=models.BooleanField(default=False,
                                      help_text='If True, users will be able to sign in to this realm user portal'),
        ),
        migrations.AlterField(
            model_name='realm',
            name='enabled_for_login',
            field=models.BooleanField(default=False,
                                      help_text='If True, users will be able to sign in to the Zentral admin console'),
        ),
    ]
