# Generated by Django 4.2.16 on 2024-09-10 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0012_realmgroupmapping_realm_group_realmgroupgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realmgroupmapping',
            name='realm_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='realms.realmgroup', verbose_name='Group'),
        ),
    ]
