# Generated by Django 4.2.18 on 2025-02-22 20:21

from django.db import migrations, models


def migrate_realm_group_scim_managed(apps, schema_editor):
    RealmGroup = apps.get_model("realms", "RealmGroup")
    RealmGroup.objects.filter(scim_external_id__isnull=False).update(scim_managed=True)


class Migration(migrations.Migration):

    dependencies = [
        ("realms", "0014_delete_realmtagmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="realmgroup",
            name="scim_managed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_realm_group_scim_managed),
    ]
