import logging
import os
import plistlib
import subprocess
import tempfile
import zipfile
from hashlib import md5, sha256

from defusedxml.ElementTree import ParseError, fromstring
from django.core.files.uploadedfile import TemporaryUploadedFile, UploadedFile

from .models import Platform

logger = logging.getLogger("zentral.contrib.mdm.app_manifest")


HASH_CHUNK_SIZE = 4 * 2**20  # 4MB


def validate_configuration(configuration):
    if configuration:
        if configuration.startswith("<dict>"):
            # to make it easier for the users
            configuration = f'<plist version="1.0">{configuration}</plist>'
        try:
            loaded_configuration = plistlib.loads(configuration.encode("utf-8"))
        except Exception:
            raise ValueError("Invalid property list")
        if not isinstance(loaded_configuration, dict):
            raise ValueError("Not a dictionary")
        return plistlib.dumps(loaded_configuration)
    else:
        return None


def ensure_tmp_file(file):
    if isinstance(file, TemporaryUploadedFile):
        return file.temporary_file_path(), False
    elif isinstance(file, UploadedFile):
        tmp_fd, tmp_filepath = tempfile.mkstemp()
        tmp_f = os.fdopen(tmp_fd, "wb")
        while True:
            chunk = file.read(2**10 * 64)
            if not chunk:
                break
            tmp_f.write(chunk)
        tmp_f.close()
        return tmp_filepath, True
    elif hasattr(file, "name"):
        return file.name, False
    raise ValueError("Unsupported file type")


def read_distribution_info(tmp_filepath):
    try:
        cp = subprocess.run(["xar", "-f", tmp_filepath, "-x", "--to-stdout", "Distribution"],
                            check=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
    except subprocess.CalledProcessError:
        raise ValueError("Could not read Distribution file")
    try:
        installer_script_elm = fromstring(cp.stdout)
    except ParseError:
        raise ValueError("Invalid Distribution file")
    # product ID product version
    product_id = product_version = None
    product_elm = installer_script_elm.find("product")
    if product_elm is None:
        logger.warning("Could not find <product/>")
        for pkg_ref in installer_script_elm.findall("pkg-ref"):
            try:
                product_id = pkg_ref.attrib["id"]
                product_version = pkg_ref.attrib["version"]
            except KeyError:
                continue
            else:
                if not product_id or not product_version:
                    continue
                else:
                    break
        else:
            raise ValueError("Could not find values for product_id and product_name")
    else:
        try:
            product_id = product_elm.attrib["id"]
            product_version = product_elm.attrib["version"]
        except KeyError as e:
            raise ValueError(f"Missing <product/> attr: {e.args[0]}")
    if not product_id:
        raise ValueError("Product ID is null")
    if not product_version:
        raise ValueError("Production version is null")
    ea_data = {
        "product_id": product_id,
        "product_version": product_version,
        "bundles": [],
    }
    for bundle in installer_script_elm.findall(".//bundle"):
        try:
            ea_data["bundles"].append({k: bundle.attrib[v]
                                       for k, v in (("version_str", "CFBundleShortVersionString"),
                                                    ("version", "CFBundleVersion"),
                                                    ("id", "id"),
                                                    ("path", "path"))})
        except KeyError as e:
            logger.error(f"Missing <bundle/> attr: {e.args[0]}")
    # name
    name = product_id
    title_elm = installer_script_elm.find("title")
    if title_elm is not None and title_elm.text:
        name = title_elm.text
    return name, [Platform.MACOS], ea_data


def read_ipa_info(tmp_filepath):
    try:
        zf = zipfile.ZipFile(tmp_filepath)
    except zipfile.BadZipFile:
        raise ValueError("Could not read IPA file")
    info_plist_path = None
    for zinfo in zf.infolist():
        if zinfo.filename.endswith("Info.plist"):
            info_plist_path = zinfo.filename
            break
    if not info_plist_path:
        raise ValueError("Could not find Info.plist")
    with zf.open(info_plist_path) as f:
        try:
            info_plist = plistlib.load(f)
        except Exception:
            raise ValueError("Could not load Info.plist")
    try:
        name = info_plist["CFBundleExecutable"]
        ea_data = {
            "product_id": info_plist["CFBundleIdentifier"],
            # CFBundleShortVersionString is the value observed in the manifests generated by Xcode.
            "product_version": info_plist["CFBundleShortVersionString"],
            "bundles": [{
                "version_str": info_plist["CFBundleShortVersionString"],
                "version": info_plist["CFBundleVersion"],
                "id": info_plist["CFBundleIdentifier"],
            }],
            "platform_identifier": f"com.apple.platform.{info_plist['DTPlatformName']}",
        }
    except KeyError as e:
        raise ValueError(f"Missing key {e.args[0]} in Info.plist")
    # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/iPhoneOSKeys.html#//apple_ref/doc/uid/TP40009252-SW11  # NOQA
    platforms = []
    device_families = info_plist.get("UIDeviceFamily")
    if not device_families:
        raise ValueError("Missing UIDeviceFamily")
    if not isinstance(device_families, list):
        device_families = [device_families]
    if 1 in device_families:
        platforms.append(Platform.IOS)
    if 2 in device_families:
        platforms.append(Platform.IPADOS)
    if 3 in device_families:
        platforms.append(Platform.TVOS)
    return name, platforms, ea_data


def compute_package_hashes(package_file, chunk_size=HASH_CHUNK_SIZE, compute_sha256=False):
    """Stream the file once, returning chunked MD5/SHA-256 digests over the
    same chunk boundaries, plus the total package size.

    With compute_sha256=True, also returns the SHA-256 digest over the whole
    file (used as the Package/EnterpriseApp identifying hash, distinct from
    the per-chunk digests).
    """
    file_chunk_size = 64 * 2**10  # 64KB
    chunk_size = (chunk_size // file_chunk_size) * file_chunk_size
    md5s = []
    sha256s = []
    md5_h = md5()
    sha256_h = sha256()
    file_sha256_h = sha256() if compute_sha256 else None
    current_size = 0
    package_size = 0
    package_file.seek(0)
    while True:
        chunk = package_file.read(file_chunk_size)
        if not chunk:
            break
        md5_h.update(chunk)
        sha256_h.update(chunk)
        if file_sha256_h is not None:
            file_sha256_h.update(chunk)
        chunk_length = len(chunk)
        current_size += chunk_length
        package_size += chunk_length
        if current_size == chunk_size:
            md5s.append(md5_h.hexdigest())
            sha256s.append(sha256_h.hexdigest())
            md5_h = md5()
            sha256_h = sha256()
            current_size = 0
    if current_size:
        md5s.append(md5_h.hexdigest())
        sha256s.append(sha256_h.hexdigest())
        if len(md5s) == 1:
            chunk_size = current_size
    file_sha256 = file_sha256_h.hexdigest() if file_sha256_h is not None else None
    return chunk_size, md5s, sha256s, package_size, file_sha256


def build_manifest_metadata(name, ea_data):
    """Assemble the manifest.items[0].metadata block from reader output.

    Pops `platform_identifier` from ea_data. Raises ValueError if any required
    Apple-spec key (kind/title/bundle-identifier/bundle-version) is missing.
    """
    metadata = {
        "kind": "software",
        "title": name,
        "bundle-identifier": ea_data["product_id"],
        "bundle-version": ea_data["product_version"],
    }
    # platform-identifier isn't in Apple's manifesturl.yaml schema, but is present
    # in the manifest generated by Xcode for mobile apps. We keep it here.
    platform_identifier = ea_data.pop("platform_identifier", None)
    if platform_identifier:
        metadata["platform-identifier"] = platform_identifier
    missing = sorted(k for k, v in metadata.items() if not isinstance(v, str) or not v)
    if missing:
        raise ValueError(f"Missing required manifest metadata: {', '.join(missing)}")
    return metadata


def read_package_info(package_file, compute_sha256=False):
    # see https://support.apple.com/lt-lt/guide/deployment/dep873c25ac4/web
    _, ext = os.path.splitext(package_file.name)
    if ext == ".pkg":
        file_opener = read_distribution_info
    elif ext == ".ipa":
        file_opener = read_ipa_info
    else:
        raise ValueError(f"Unsupported file extension: {ext}")
    tmp_filepath, cleanup_tmp_file = ensure_tmp_file(package_file)
    try:
        name, platforms, ea_data = file_opener(tmp_filepath)
    finally:
        if cleanup_tmp_file:
            os.unlink(tmp_filepath)
    chunk_size, md5s, sha256s, package_size, package_sha256 = compute_package_hashes(
        package_file, compute_sha256=compute_sha256,
    )
    metadata = build_manifest_metadata(name, ea_data)
    # md5-size and sha256-size share a single chunk boundary because we compute
    # both hashers in lockstep over the same chunks.
    asset = {"kind": "software-package",
             "md5-size": chunk_size, "md5s": md5s,
             "sha256-size": chunk_size, "sha256s": sha256s}
    manifest = {"items": [{"assets": [asset], "metadata": metadata}]}
    ea_data["manifest"] = manifest
    ea_data["package_size"] = package_size
    if compute_sha256:
        ea_data["package_sha256"] = package_sha256
    return name, platforms, ea_data
