# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0001_squashed_0010_auto_20161129_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedprobe',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
