# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Probe',
            new_name='ProbeSource',
        ),
    ]
