# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0002_auto_20161207_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedprobe',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='feedprobe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
