# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0002_auto_20160602_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probesource',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterField(
            model_name='probesource',
            name='body',
            field=models.TextField(),
        ),
    ]
