# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0003_auto_20161207_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='probesource',
            name='feed_probe',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='probes.FeedProbe'),
        ),
        migrations.AddField(
            model_name='probesource',
            name='feed_probe_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
