# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0004_auto_20161207_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedimport',
            name='feed',
        ),
        migrations.AddField(
            model_name='feed',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FeedImport',
        ),
    ]
