# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 13:43
from __future__ import unicode_literals

from django.db import migrations
from zentral.core.probes import probe_classes
from zentral.core.probes.base import BaseProbe


def load_probe(source):
    for probe_cls in probe_classes.values():
        if probe_cls == BaseProbe:
            continue
        try:
            return probe_cls(source)
        except ValueError:
            pass
    return BaseProbe(source)


def set_probe_source_apps_event_type_model(apps, schema_editor):
    ProbeSource = apps.get_model("probes", "ProbeSource")
    for ps in ProbeSource.objects.all():
        probe = load_probe(ps)
        ps.model = probe.get_model()
        ps.apps = [etc.get_app_display() for etc in probe.event_type_classes]
        ps.event_types = [etc.event_type for etc in probe.event_type_classes]
        ps.save()


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0005_auto_20161104_1343'),
    ]

    operations = [
        migrations.RunPython(set_probe_source_apps_event_type_model),
    ]
