# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0005_auto_20161209_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
