# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0006_auto_20161104_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probesource',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=32),
        ),
    ]
