# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0008_auto_20161210_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='feedprobe',
            options={'ordering': ('model', 'name')},
        ),
    ]
