# Generated by Django 3.2.12 on 2022-03-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0011_auto_20190925_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedprobe',
            name='body',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='probesource',
            name='body',
            field=models.JSONField(editable=False),
        ),
    ]
