# Generated by Django 4.2.21 on 2025-05-26 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0013_remove_feed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                ("name", models.CharField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("backend_kwargs", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("HTTP_POST", "HTTP POST"),
                            ("SLACK_INCOMING_WEBHOOK", "Slack incoming webhook"),
                        ]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="probesource",
            name="actions",
            field=models.ManyToManyField(blank=True, to="probes.action"),
        ),
    ]
