# Generated by Django 4.2.21 on 2025-06-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("probes", "0014_action_probesource_actions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="feedprobe",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="feedprobe",
            name="feed",
        ),
        migrations.RemoveField(
            model_name="probesource",
            name="feed_probe",
        ),
        migrations.RemoveField(
            model_name="probesource",
            name="feed_probe_last_synced_at",
        ),
        migrations.RemoveField(
            model_name="probesource",
            name="feed_probe_update_available",
        ),
        migrations.RemoveField(
            model_name="probesource",
            name="model",
        ),
        migrations.DeleteModel(
            name="Feed",
        ),
        migrations.DeleteModel(
            name="FeedProbe",
        ),
    ]
