#!/bin/bash

# postinstall

# unload com.google.santad.plist
/bin/launchctl unload "/Library/LaunchDaemons/com.google.santad.plist"

# sleep, because …
sleep 1

# do enrollment
/usr/local/zentral/santa/enroll.py

# copy old style configuration
cp "/usr/local/zentral/santa/config.plist" "/var/db/santa/config.plist"
# fix old style configuration permissions
chmod 0644 /var/db/santa/config.plist

# load com.google.santad.plist
/bin/launchctl load -w "/Library/LaunchDaemons/com.google.santad.plist"

# write zentral base url
defaults write /Library/Preferences/io.zentral.plist base_url "https://%TLS_HOSTNAME%"

# force santa sync (=> preflight => machine_id => serial number)
/usr/local/bin/santactl sync

exit 0
