# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-07 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20171107_2157'),
        ('mdm', '0002_enrolleddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDMSCEPChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mdm_scep_challenge', to='inventory.EnrollmentSecret')),
            ],
        ),
        migrations.CreateModel(
            name='OTAEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ota_enrollment', to='inventory.EnrollmentSecret')),
            ],
        ),
        migrations.CreateModel(
            name='OTASCEPChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment_secret', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ota_scep_challenge', to='inventory.EnrollmentSecret')),
                ('ota_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.OTAEnrollment')),
            ],
        ),
        migrations.AddField(
            model_name='mdmscepchallenge',
            name='ota_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.OTAEnrollment'),
        ),
    ]
