# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0008_auto_20180513_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenrollmentsession',
            name='imei',
            field=models.TextField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='depenrollmentsession',
            name='language',
            field=models.CharField(default='???', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depenrollmentsession',
            name='meid',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='depenrollmentsession',
            name='product',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depenrollmentsession',
            name='version',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='imei',
            field=models.TextField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='language',
            field=models.CharField(default='???', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='meid',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='product',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='version',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
