# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0009_auto_20180515_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenrollmentsession',
            name='language',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='otaenrollmentsession',
            name='language',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
