# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0010_auto_20180515_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='checkout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
