# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0013_auto_20180515_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kernelextensionpolicy',
            name='allowed_kernel_extensions',
            field=models.ManyToManyField(blank=True, to='mdm.KernelExtension'),
        ),
        migrations.AlterField(
            model_name='kernelextensionpolicy',
            name='allowed_teams',
            field=models.ManyToManyField(blank=True, to='mdm.KernelExtensionTeam'),
        ),
    ]
