# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mdm', '0014_auto_20180515_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledDeviceArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_id', models.PositiveIntegerField()),
                ('artifact_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('enrolled_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.EnrolledDevice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='installeddeviceartifact',
            unique_together=set([('enrolled_device', 'artifact_content_type', 'artifact_id')]),
        ),
    ]
