# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-12 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0015_auto_20180603_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenrollmentsession',
            name='imei',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='depenrollmentsession',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='otaenrollmentsession',
            name='imei',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='otaenrollmentsession',
            name='language',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
