# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-28 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0018_auto_20180706_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depdevice',
            name='profile_status',
            field=models.CharField(choices=[('empty', 'Empty'), ('assigned', 'Assigned'), ('pushed', 'Pushed'), ('removed', 'Removed')], default='empty', editable=False, max_length=64),
        ),
    ]
