# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-16 18:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_auto_20180704_1049'),
        ('mdm', '0020_auto_20180911_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', django.contrib.postgres.fields.jsonb.JSONField()),
                ('source_payload_identifier', models.TextField(editable=False)),
                ('payload_display_name', models.TextField(blank=True, editable=False, null=True)),
                ('payload_description', models.TextField(blank=True, editable=False, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trashed_at', models.DateTimeField(editable=False, null=True)),
                ('meta_business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MetaBusinessUnit')),
            ],
        ),
        migrations.AlterField(
            model_name='kernelextensionpolicy',
            name='meta_business_unit',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='kernel_extension_policy', to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationprofile',
            unique_together=set([('meta_business_unit', 'source_payload_identifier')]),
        ),
    ]
