# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20180927_0935'),
        ('mdm', '0021_auto_20180916_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depprofile',
            name='virtual_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.DEPVirtualServer'),
        ),
        migrations.AlterUniqueTogether(
            name='mdmenrollmentpackage',
            unique_together=set([('meta_business_unit', 'builder', 'trashed_at')]),
        ),
    ]
