# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-27 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0022_auto_20180927_0935'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mdmenrollmentpackage',
            unique_together=set([]),
        ),
    ]
