# Generated by Django 2.2.10 on 2020-03-03 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_realmauthenticationsession_backend_state'),
        ('mdm', '0024_auto_20190227_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaenrollment',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.Realm'),
        ),
    ]
