# Generated by Django 2.2.10 on 2020-03-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0002_realmauthenticationsession_backend_state'),
        ('inventory', '0049_machine_snapshot_certificates_on_delete_cascade'),
        ('mdm', '0025_otaenrollment_realm'),
    ]

    operations = [
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='phase2_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.EnrollmentSecretRequest'),
        ),
        migrations.AddField(
            model_name='otaenrollmentsession',
            name='realm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.RealmUser'),
        ),
        migrations.AlterField(
            model_name='otaenrollmentsession',
            name='status',
            field=models.CharField(choices=[('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2'), ('PHASE_2_SCEP_VERIFIED', 'Phase 2 SCEP verified'), ('PHASE_3', 'Phase 3'), ('PHASE_3_SCEP_VERIFIED', 'Phase 3 SCEP verified'), ('AUTHENTICATED', 'Authenticated'), ('COMPLETED', 'Completed')], max_length=64),
        ),
    ]
