# Generated by Django 2.2.10 on 2020-03-05 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0028_depenrollmentsession_realm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationprofile',
            name='install_before_setup_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='admin_full_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='admin_password_hash',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='admin_short_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='realm_user_is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='depprofile',
            name='use_realm_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='awaiting_configuration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='enrollment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='enrollment_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='kernelextensionpolicy',
            name='install_before_setup_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mdmenrollmentpackage',
            name='install_before_setup_assistant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='configurationprofile',
            name='meta_business_unit',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mdm_configurationprofile', to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='configurationprofile',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='kernelextensionpolicy',
            name='meta_business_unit',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mdm_kernelextensionpolicy', to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='kernelextensionpolicy',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='mdmenrollmentpackage',
            name='meta_business_unit',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mdm_mdmenrollmentpackage', to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='mdmenrollmentpackage',
            name='version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('request_type', models.CharField(max_length=128)),
                ('dictionary', django.contrib.postgres.fields.jsonb.JSONField()),
                ('time', models.DateTimeField(null=True)),
                ('result_time', models.DateTimeField(null=True)),
                ('status_code', models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('Error', 'Error'), ('CommandFormatError', 'Command format error'), ('NotNow', 'Not now')], max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.EnrolledDevice')),
            ],
        ),
        migrations.AddField(
            model_name='deviceartifactcommand',
            name='command',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mdm.DeviceCommand'),
        ),
    ]
