# Generated by Django 2.2.10 on 2020-03-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0030_auto_20200305_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceartifactcommand',
            name='command_time',
        ),
        migrations.RemoveField(
            model_name='deviceartifactcommand',
            name='command_uuid',
        ),
        migrations.RemoveField(
            model_name='deviceartifactcommand',
            name='enrolled_device',
        ),
        migrations.RemoveField(
            model_name='deviceartifactcommand',
            name='result_time',
        ),
        migrations.RemoveField(
            model_name='deviceartifactcommand',
            name='status_code',
        ),
        migrations.AlterField(
            model_name='deviceartifactcommand',
            name='command',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mdm.DeviceCommand'),
        ),
    ]
