# Generated by Django 2.2.10 on 2020-03-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0031_auto_20200305_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
