# Generated by Django 2.2.18 on 2021-05-26 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0034_auto_20200305_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='bootstrap_token',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depprofile',
            name='skip_setup_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Accessibility', 'Accessibility'), ('Android', 'Android'), ('Appearance', 'Appearance'), ('AppleID', 'AppleID'), ('Biometric', 'Biometric'), ('DeviceToDeviceMigration', 'DeviceToDeviceMigration'), ('Diagnostics', 'Diagnostics'), ('DisplayTone', 'DisplayTone'), ('FileVault', 'FileVault'), ('HomeButtonSensitivity', 'HomeButtonSensitivity'), ('iCloudDiagnostics', 'iCloudDiagnostics'), ('iCloudStorage', 'iCloudStorage'), ('iMessageAndFaceTime', 'iMessageAndFaceTime'), ('Location', 'Location'), ('MessagingActivationUsingPhoneNumber', 'MessagingActivationUsingPhoneNumber'), ('OnBoarding', 'OnBoarding'), ('Passcode', 'Passcode'), ('Payment', 'Payment'), ('Privacy', 'Privacy'), ('Restore', 'Restore'), ('RestoreCompleted', 'RestoreCompleted'), ('ScreenSaver', 'ScreenSaver'), ('ScreenTime', 'ScreenTime'), ('SIMSetup', 'SIMSetup'), ('Siri', 'Siri'), ('SoftwareUpdate', 'SoftwareUpdate'), ('TapToSetup', 'TapToSetup'), ('TOS', 'TOS'), ('TVHomeScreenSync', 'TVHomeScreenSync'), ('TVProviderSignIn', 'TVProviderSignIn'), ('TVRoom', 'TVRoom'), ('UpdateCompleted', 'UpdateCompleted'), ('WatchMigration', 'WatchMigration'), ('Welcome', 'Welcome'), ('Zoom', 'Zoom')], max_length=64), editable=False, size=None),
        ),
    ]
