# Generated by Django 2.2.18 on 2021-06-01 05:44

import django.contrib.postgres.fields
from django.db import migrations, models
import zentral.contrib.mdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0036_auto_20210530_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('iOS', 'iOS'), ('iPadOS', 'iPadOS'), ('macOS', 'macOS'), ('tvOS', 'tvOS')], max_length=64), default=zentral.contrib.mdm.models.Platform.all_values, size=None),
        ),
    ]
