# Generated by Django 2.2.20 on 2021-06-01 18:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0037_auto_20210601_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='artifact_operation',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Removal', 'Removal')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='error_chain',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='usercommand',
            name='artifact_operation',
            field=models.CharField(choices=[('Installation', 'Installation'), ('Removal', 'Removal')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usercommand',
            name='error_chain',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
