# Generated by Django 2.2.24 on 2021-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0040_auto_20210606_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseapp',
            name='filename',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
    ]
