# Generated by Django 2.2.24 on 2021-06-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0041_enterpriseapp_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='not_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usercommand',
            name='not_before',
            field=models.DateTimeField(null=True),
        ),
    ]
