# Generated by Django 2.2.24 on 2021-06-07 10:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0042_auto_20210606_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseapp',
            name='bundles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
