# Generated by Django 2.2.24 on 2021-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0044_enrolleddevice_declarative_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceartifact',
            name='status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('AwaitingConfirmation', 'AwaitingConfirmation'), ('Installed', 'Installed')], default='Acknowledged', max_length=64),
        ),
        migrations.AddField(
            model_name='userartifact',
            name='status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('AwaitingConfirmation', 'AwaitingConfirmation'), ('Installed', 'Installed')], default='Acknowledged', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='deviceartifact',
            unique_together={('enrolled_device', 'artifact_version')},
        ),
        migrations.AlterUniqueTogether(
            name='userartifact',
            unique_together={('enrolled_user', 'artifact_version')},
        ),
    ]
