# Generated by Django 2.2.24 on 2021-06-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realms', '0006_realmgroupmapping'),
        ('mdm', '0045_auto_20210610_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userenrollment',
            name='realm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='realms.Realm'),
        ),
        migrations.AddField(
            model_name='userenrollmentsession',
            name='access_token',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userenrollmentsession',
            name='managed_apple_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollmentsession',
            name='status',
            field=models.CharField(choices=[('ACCOUNT_DRIVEN_START', 'Account-based onboarding initiated'), ('ACCOUNT_DRIVEN_AUTHENTICATED', 'Account-based onboarding authenticated'), ('STARTED', 'Started'), ('SCEP_VERIFIED', 'SCEP verified'), ('AUTHENTICATED', 'Authenticated'), ('COMPLETED', 'Completed')], max_length=64),
        ),
    ]
