# Generated by Django 2.2.24 on 2021-06-12 11:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0046_auto_20210610_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='activation',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='declaration_items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='declarations_token',
            field=models.UUIDField(null=True),
        ),
    ]
