# Generated by Django 3.2.14 on 2022-08-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_alter_metabusinessunit_name'),
        ('realms', '0007_auto_20220329_0639'),
        ('mdm', '0050_auto_20220730_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReEnrollmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('STARTED', 'Started'),
                                                     ('SCEP_VERIFIED', 'SCEP verified'),
                                                     ('AUTHENTICATED', 'Authenticated'),
                                                     ('COMPLETED', 'Completed')], max_length=64)),
                ('dep_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='mdm.depenrollment')),
                ('enrolled_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      to='mdm.enrolleddevice')),
                ('enrollment_secret', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT,
                                                           related_name='reenrollment_session',
                                                           to='inventory.enrollmentsecret')),
                ('ota_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='mdm.otaenrollment')),
                ('realm_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                 to='realms.realmuser')),
                ('scep_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                   related_name='+', to='inventory.enrollmentsecretrequest')),
                ('user_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                      to='mdm.userenrollment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
