# Generated by Django 3.2.14 on 2022-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0051_reenrollmentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecommand',
            name='result',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='usercommand',
            name='result',
            field=models.BinaryField(null=True),
        ),
    ]
