# Generated by Django 3.2.14 on 2023-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0056_auto_20230108_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolleddevice',
            name='udid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='enrolleduser',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
