# Generated by Django 3.2.14 on 2022-12-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0056_auto_20220929_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledDeviceAssetAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.asset')),
                ('enrolled_device', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='mdm.enrolleddevice')),
            ],
            options={
                'unique_together': {('enrolled_device', 'asset')},
            },
        ),
    ]
