# Generated by Django 3.2.18 on 2023-05-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0058_auto_20230123_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='build_version',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='build_version_extra',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='os_version_extra',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='softwareupdate',
            name='extra',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='softwareupdate',
            name='prerequisite_build',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='softwareupdate',
            unique_together={
                ('platform', 'major', 'minor', 'patch', 'extra', 'prerequisite_build', 'public', 'availability')
            },
        ),
    ]
