# Generated by Django 3.2.18 on 2023-06-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0060_auto_20230221_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='client_capabilities',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='client_capabilities',
            field=models.JSONField(null=True),
        ),
    ]
