# Generated by Django 4.1.9 on 2023-06-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0061_auto_20230607_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
