# Generated by Django 4.1.9 on 2023-06-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0063_depenrollment_ios_min_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depdevice',
            name='asset_tag',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='color',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='device_family',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='model',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='os',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='model',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
