# Generated by Django 4.1.9 on 2023-06-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0064_depdevice_asset_tag_depdevice_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depvirtualserver',
            name='default_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='mdm.depenrollment'),
        ),
    ]
