# Generated by Django 4.1.9 on 2023-08-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0068_reenrollmentsession_first_enrolled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='pending_firmware_password',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='pending_firmware_password_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
