# Generated by Django 4.1.12 on 2023-11-14 15:51

import django.contrib.postgres.fields
from django.db import migrations, models
import zentral.contrib.mdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0070_enterpriseapp_package_sha256_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('iOS', 'iOS'), ('iPadOS', 'iPadOS'), ('macOS', 'macOS'), ('tvOS', 'tvOS')], max_length=64), default=zentral.contrib.mdm.models.get_platform_values, size=None),
        ),
        migrations.AlterField(
            model_name='asset',
            name='supported_platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('iOS', 'iOS'), ('iPadOS', 'iPadOS'), ('macOS', 'macOS'), ('tvOS', 'tvOS')], max_length=64), size=None),
        ),
        migrations.AlterField(
            model_name='enrolleddevice',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('iPadOS', 'iPadOS'), ('macOS', 'macOS'), ('tvOS', 'tvOS')], max_length=64),
        ),
        migrations.AlterField(
            model_name='softwareupdate',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('iPadOS', 'iPadOS'), ('macOS', 'macOS'), ('tvOS', 'tvOS')], max_length=64),
        ),
    ]
