# Generated by Django 4.2.8 on 2024-02-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0073_alter_softwareupdate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenrollment',
            name='ios_max_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='max. required iOS version'),
        ),
        migrations.AddField(
            model_name='depenrollment',
            name='macos_max_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='max. required macOS version'),
        ),
        migrations.AlterField(
            model_name='depenrollment',
            name='ios_min_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='min. required iOS version'),
        ),
        migrations.AlterField(
            model_name='depenrollment',
            name='macos_min_version',
            field=models.CharField(blank=True, max_length=32, verbose_name='min. required macOS version'),
        ),
    ]
