# Generated by Django 4.2.13 on 2024-06-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0078_depenrollment_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushcertificate',
            name='signed_csr',
        ),
        migrations.RemoveField(
            model_name='pushcertificate',
            name='signed_csr_updated_at',
        ),
    ]
