# Generated by Django 4.2.13 on 2024-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0079_remove_pushcertificate_signed_csr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scepconfig',
            name='provisioning_uid',
            field=models.CharField(editable=False, max_length=256, null=True, unique=True),
        ),
    ]
