# Generated by Django 4.2.13 on 2024-06-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0078_file_cdhash'),
        ('mdm', '0081_pushcertificate_provisioning_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenrollment',
            name='enrollment_secret',
            field=models.OneToOneField(editable=False,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       related_name='dep_enrollment', to='inventory.enrollmentsecret'),
        ),
        migrations.AlterField(
            model_name='otaenrollment',
            name='enrollment_secret',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='ota_enrollment', to='inventory.enrollmentsecret'),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='enrollment_secret',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user_enrollment', to='inventory.enrollmentsecret'),
        ),
    ]
