# Generated by Django 4.2.17 on 2025-01-18 13:09

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import zentral.contrib.mdm.models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0083_realmgrouptagmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('identifier', models.TextField(db_index=True)),
                ('server_token', models.TextField(unique=True)),
                ('payload', models.JSONField()),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='declaration', to='mdm.artifactversion')),
            ],
        ),
        migrations.AlterField(
            model_name='artifact',
            name='type',
            field=models.CharField(choices=[('Activation', 'Activation'),
                                            ('Asset', 'Asset'),
                                            ('Configuration', 'Configuration'),
                                            ('Data Asset', 'Data Asset'),
                                            ('Enterprise App', 'Enterprise App'),
                                            ('Configuration (manual)', 'Manual Configuration'),
                                            ('Profile', 'Profile'),
                                            ('Store App', 'Store App')],
                                   max_length=64),
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PLIST', 'PLIST (.plist)'),
                                                   ('ZIP', 'ZIP archive (.zip)')],
                                          max_length=256)),
                ('file', models.FileField(upload_to=zentral.contrib.mdm.models.data_asset_path)),
                ('filename', models.TextField()),
                ('file_size', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('file_sha256', models.CharField(max_length=64)),
                ('artifact_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                          related_name='data_asset', to='mdm.artifactversion')),
            ],
        ),
        migrations.CreateModel(
            name='DeclarationRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=256,
                                                validators=[django.core.validators.MinLengthValidator(1)]),
                    size=None)
                 ),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.artifact')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mdm.declaration')),
            ],
            options={
                'unique_together': {('declaration', 'key')},
            },
        ),
    ]
