# Generated by Django 4.2.18 on 2025-03-01 13:42

from django.db import migrations, models
import zentral.contrib.mdm.models
import zentral.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0085_deviceartifact_install_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataasset",
            name="file",
            field=models.FileField(
                storage=zentral.utils.storage.select_dist_storage,
                upload_to=zentral.contrib.mdm.models.data_asset_path,
            ),
        ),
        migrations.AlterField(
            model_name="enterpriseapp",
            name="package",
            field=models.FileField(
                storage=zentral.utils.storage.select_dist_storage,
                upload_to=zentral.contrib.mdm.models.enterprise_application_package_path,
            ),
        ),
    ]
