# Generated by Django 4.2.18 on 2025-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0086_alter_dataasset_file_alter_enterpriseapp_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depdevice',
            name='color',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='depdevice',
            name='device_family',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='depdevice',
            name='model',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='depdevice',
            name='os',
            field=models.CharField(default='', max_length=256),
        ),
    ]
