# Generated by Django 4.2.18 on 2025-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0087_alter_depdevice_color_alter_depdevice_device_family_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depdevice',
            options={'ordering': ('serial_number',), 'permissions': [('disown_depdevice', 'Can disown a DEP device')]},
        ),
        migrations.AddField(
            model_name='depdevice',
            name='disowned_at',
            field=models.DateTimeField(null=True),
        ),
    ]
