# Generated by Django 4.2.23 on 2025-09-19 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0090_acmeissuer_scepissuer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrolleddevice",
            options={
                "permissions": [
                    ("view_admin_password", "Can view admin password"),
                    ("view_filevault_prk", "Can view FileVault PRK"),
                    ("view_recovery_password", "Can view recovery password"),
                ]
            },
        ),
        migrations.RemoveField(
            model_name="depenrollment",
            name="admin_password_hash",
        ),
        migrations.AddField(
            model_name="depenrollment",
            name="admin_password_complexity",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddField(
            model_name="depenrollment",
            name="admin_password_rotation_delay",
            field=models.IntegerField(
                default=60,
                help_text="When an admin password is read, delay in minutes after which a command to rotate the password on the device will be scheduled. 60 min by default, 1 day max (1440 min). If 0, no automatic password rotation will be scheduled.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1440),
                ],
            ),
        ),
        migrations.AddField(
            model_name="depenrollment",
            name="hidden_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrolleddevice",
            name="admin_password",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="enrolleddevice",
            name="admin_password_updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
