# Generated by Django 4.2.24 on 2025-09-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0091_alter_enrolleddevice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolleddevice",
            name="last_ip",
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name="enrolleduser",
            name="last_ip",
            field=models.GenericIPAddressField(null=True, unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name="enrolleduser",
            name="enrolled_device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="mdm.enrolleddevice",
            ),
        ),
    ]
