# Generated by Django 4.2.24 on 2025-09-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0092_enrolleddevice_last_ip_enrolleduser_last_ip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="depenrollment",
            name="scep_config",
        ),
        migrations.RemoveField(
            model_name="depenrollment",
            name="scep_verification",
        ),
        migrations.RemoveField(
            model_name="otaenrollment",
            name="scep_config",
        ),
        migrations.RemoveField(
            model_name="otaenrollment",
            name="scep_verification",
        ),
        migrations.RemoveField(
            model_name="userenrollment",
            name="scep_config",
        ),
        migrations.RemoveField(
            model_name="userenrollment",
            name="scep_verification",
        ),
    ]
