# Generated by Django 4.2.24 on 2025-09-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0093_remove_depenrollment_scep_config_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="type",
            field=models.CharField(
                choices=[
                    ("Activation", "Activation"),
                    ("Asset", "Asset"),
                    ("Certificate Asset", "Cert Asset"),
                    ("Configuration", "Configuration"),
                    ("Data Asset", "Data Asset"),
                    ("Enterprise App", "Enterprise App"),
                    ("Configuration (manual)", "Manual Configuration"),
                    ("Profile", "Profile"),
                    ("Store App", "Store App"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="CertAsset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.JSONField(blank=True, default=list)),
                (
                    "subject_alt_name",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="SubjectAltName"
                    ),
                ),
                (
                    "accessible",
                    models.CharField(
                        choices=[
                            ("Default", "Default"),
                            ("AfterFirstUnlock", "After first unlock"),
                        ],
                        default="Default",
                    ),
                ),
                (
                    "acme_issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mdm.acmeissuer",
                        verbose_name="ACME issuer",
                    ),
                ),
                (
                    "artifact_version",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cert_asset",
                        to="mdm.artifactversion",
                    ),
                ),
                (
                    "scep_issuer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mdm.scepissuer",
                        verbose_name="SCEP issuer",
                    ),
                ),
            ],
        ),
    ]
