# Generated by Django 4.2.25 on 2025-10-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0094_alter_artifact_type_certasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprint",
            name="default_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mdm.location",
                verbose_name="Default apps & books location",
            ),
        ),
        migrations.AddField(
            model_name="blueprint",
            name="legacy_profiles_via_ddm",
            field=models.BooleanField(
                default=True, verbose_name="Distribute legacy profiles via DDM"
            ),
        ),
        migrations.DeleteModel(
            name="EnrolledDeviceLocationAssetAssociation",
        ),
    ]
