# Generated by Django 4.2.25 on 2025-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0095_blueprint_default_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acmeissuer",
            name="backend",
            field=models.CharField(
                choices=[
                    ("DIGICERT", "Digicert One - Trust Lifecycle Manager"),
                    ("IDENT", "IDent"),
                    ("MICROSOFT_CA", "Microsoft CA"),
                    ("OKTA_CA", "Okta CA"),
                    ("STATIC_CHALLENGE", "Static challenge"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="scepissuer",
            name="backend",
            field=models.CharField(
                choices=[
                    ("DIGICERT", "Digicert One - Trust Lifecycle Manager"),
                    ("IDENT", "IDent"),
                    ("MICROSOFT_CA", "Microsoft CA"),
                    ("OKTA_CA", "Okta CA"),
                    ("STATIC_CHALLENGE", "Static challenge"),
                ]
            ),
        ),
    ]
