# Generated by Django 4.2.26 on 2025-11-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0096_alter_acmeissuer_backend_alter_scepissuer_backend"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="devicecommand",
            index=models.Index(
                condition=models.Q(
                    ("time__isnull", True),
                    ("result_time__isnull", True),
                    _connector="OR",
                ),
                fields=["enrolled_device_id"],
                name="apns_device_opti",
            ),
        ),
        migrations.AddIndex(
            model_name="usercommand",
            index=models.Index(
                condition=models.Q(
                    ("time__isnull", True),
                    ("result_time__isnull", True),
                    _connector="OR",
                ),
                fields=["enrolled_user_id"],
                name="apns_user_opti",
            ),
        ),
    ]
