# Generated by Django 5.2.9 on 2025-12-17 11:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0097_devicecommand_apns_device_opti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depenrollment',
            name='skip_setup_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
    ]
