# Generated by Django 5.2.9 on 2025-12-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0098_alter_depenrollment_skip_setup_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="depdevice",
            options={
                "ordering": ("serial_number", "virtual_server__name"),
                "permissions": [("disown_depdevice", "Can disown a DEP device")],
            },
        ),
        migrations.AlterField(
            model_name="depdevice",
            name="serial_number",
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name="depdevice",
            unique_together={("virtual_server", "serial_number")},
        ),
    ]
