# Generated by Django 5.2.9 on 2026-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0099_alter_depdevice_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depenrollment",
            name="allow_pairing",
            field=models.BooleanField(
                default=True,
                help_text="Allow the device to connect to other computers. In iOS 13, this property was deprecated.",
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="auto_advance_setup",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If set to true, the device will tell Setup Assistant to automatically advance though its screens."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="await_device_configured",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, the device will not continue in Setup Assistant until the MDM server sends a command"
                    " that states the device is configured. Required when using the authenticated user details or for"
                    " the extra admin."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="include_tls_certificates",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If true, only the configured TLS certificates for the Zentral instance will be used by the device"
                    " when evaluating the trust of the connection to the MDM server URL. Otherwise, the device uses"
                    " the built-in root certificates."
                ),
                verbose_name="Include anchor certs",
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="is_mandatory",
            field=models.BooleanField(
                default=True,
                help_text="If true, the user may not skip applying the profile returned by the MDM server.",
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="is_mdm_removable",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If false, the MDM payload delivered by the configuration URL cannot be removed by the user via"
                    " the user interface on the device."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="is_multi_user",
            field=models.BooleanField(
                default=False,
                help_text="If true, tells the device to configure for Shared iPad.",
            ),
        ),
        migrations.AlterField(
            model_name="depenrollment",
            name="is_supervised",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If true, the device must be supervised. In iOS 13, all DEP devices are supervised and the OS will"
                    " ignore this."
                ),
            ),
        ),
    ]
