# Generated by Django 5.2.9 on 2026-02-01 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mdm", "0100_alter_depenrollment_allow_pairing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="type",
            field=models.CharField(
                choices=[
                    ("Activation", "Activation"),
                    ("Asset", "Asset"),
                    ("Certificate Asset", "Cert Asset"),
                    ("Configuration", "Configuration"),
                    ("Data Asset", "Data Asset"),
                    ("Enterprise App", "Enterprise App"),
                    ("Configuration (manual)", "Manual Configuration"),
                    ("Profile", "Profile"),
                    ("Provisioning Profile", "Provisioning Profile"),
                    ("Store App", "Store App"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="ProvisioningProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.BinaryField()),
                ("name", models.TextField()),
                ("uuid", models.UUIDField()),
                ("content", models.BinaryField()),
                (
                    "artifact_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_profile",
                        to="mdm.artifactversion",
                    ),
                ),
            ],
        ),
    ]
