# Generated by Django 5.2.11 on 2026-02-24 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0102_alter_enrolleddevice_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enrolleddevice",
            options={
                "permissions": [
                    ("view_admin_password", "Can view admin password"),
                    ("view_filevault_prk", "Can view FileVault PRK"),
                    ("view_recovery_password", "Can view recovery password"),
                    ("view_device_lock_pin", "Can view device lock pin"),
                ]
            },
        ),
    ]
