# Generated by Django 5.2.14 on 2026-05-30 13:56

import uuid
import zentral.contrib.mdm.models
import zentral.utils.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0103_alter_enrolleddevice_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True)),
                ("type", models.CharField(choices=[("IPA", "Ipa"), ("PKG", "Pkg")], max_length=3)),
                (
                    "file",
                    models.FileField(
                        storage=zentral.utils.storage.select_dist_storage,
                        upload_to=zentral.contrib.mdm.models.package_path,
                    ),
                ),
                ("source_uri", models.TextField(default="")),
                ("sha256", models.CharField(max_length=64, unique=True)),
                ("size", models.BigIntegerField()),
                ("filename", models.TextField()),
                ("product_id", models.TextField()),
                ("product_version", models.TextField()),
                ("bundles", models.JSONField(default=list)),
                ("manifest", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("name",),
                "indexes": [
                    models.Index(fields=["product_id", "product_version"], name="mdm_package_product_344360_idx")
                ],
            },
        ),
    ]
