# Generated by Django 5.2.14 on 2026-05-30 15:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mdm", "0104_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageRef",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "key",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=256, validators=[django.core.validators.MinLengthValidator(1)]
                        ),
                        size=None,
                    ),
                ),
                ("declaration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mdm.declaration")),
                ("package", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mdm.package")),
            ],
            options={
                "unique_together": {("declaration", "key")},
            },
        ),
    ]
