# Generated by Django 5.2.16 on 2026-08-05 08:23

import django.core.validators
import zentral.contrib.mdm.models
from django.db import migrations, models


def disable_prk_reveal_rotation(apps, schema_editor):
    # existing configurations keep their current behaviour, only new ones rotate by default
    FileVaultConfig = apps.get_model("mdm", "FileVaultConfig")
    FileVaultConfig.objects.update(prk_reveal_rotation_delay=0)


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0107_recoverypasswordconfig_reveal_rotation_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='filevaultconfig',
            name='prk_reveal_rotation_delay',
            field=models.IntegerField(default=60, help_text='When a PRK is read, delay in minutes after which a command to rotate the PRK on the device will be scheduled. 60 min by default, 5 min min., 1 day max (1440 min). If 0, no automatic PRK rotation will be scheduled.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440), zentral.contrib.mdm.models.validate_reveal_rotation_delay], verbose_name='PRK rotation delay after reveal (min)'),
        ),
        migrations.RunPython(disable_prk_reveal_rotation, migrations.RunPython.noop),
    ]
