# Generated by Django 5.2.16 on 2026-08-20 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0108_filevaultconfig_prk_reveal_rotation_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='depenrollment',
            name='await_declarations_timeout',
            field=models.IntegerField(default=5, help_text='While the device awaits the DeviceConfigured command, delay in minutes after which it is sent even if the declarations scoped to the Setup Assistant have not been reported. The device is notified as soon as it reports them, so this deadline is only reached when it reports nothing. 5 min by default, 1 min min, 1 hour max.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
