# Generated by Django 5.2.17 on 2026-08-25 05:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0108_filevaultconfig_prk_reveal_rotation_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='depdevice',
            name='bluetooth_mac_address',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='eid',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='ethernet_mac_address',
            field=models.CharField(default='', max_length=23),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='imei',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='is_replacement_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='mdm_migration_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='meid',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='released_by_replacement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depdevice',
            name='wifi_mac_address',
            field=models.CharField(default='', max_length=23),
        ),
    ]
