# Generated by Django 5.2.17 on 2026-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0109_depdevice_protocol_10_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceartifact',
            name='force_install_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userartifact',
            name='force_install_requested_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='deviceartifact',
            name='status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('AwaitingConfirmation', 'Awaiting Confirmation'), ('Installed', 'Installed'), ('Uninstalled', 'Uninstalled'), ('Failed', 'Failed'), ('RemovalFailed', 'Removal Failed')], default='Acknowledged', max_length=64),
        ),
        migrations.AlterField(
            model_name='userartifact',
            name='status',
            field=models.CharField(choices=[('Acknowledged', 'Acknowledged'), ('AwaitingConfirmation', 'Awaiting Confirmation'), ('Installed', 'Installed'), ('Uninstalled', 'Uninstalled'), ('Failed', 'Failed'), ('RemovalFailed', 'Removal Failed')], default='Acknowledged', max_length=64),
        ),
    ]
