# Generated by Django 5.2.17 on 2026-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0110_deviceartifact_force_install_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='status_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='enrolleddevice',
            name='status_items_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='status_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='status_items_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
