# Generated by Django 5.2.17 on 2026-09-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm', '0111_enrolleddevice_status_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolleddevice',
            name='status_items_full_report_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrolleduser',
            name='status_items_full_report_at',
            field=models.DateTimeField(null=True),
        ),
    ]
