# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='user',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
    ]
