# Generated by Django 4.1.9 on 2023-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items_per_page',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
