# Generated by Django 5.2.9 on 2026-01-13 14:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def set_id_defaults(apps, schema_editor):  # pragma: no cover
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    APIToken = apps.get_model("accounts", "APIToken")
    for token in APIToken.objects.all().iterator():
        token.id = uuid.uuid4()
        token.save()


def reverse_id_defaults(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_id_defaults, reverse_id_defaults),
        migrations.AlterField(
            model_name='apitoken',
            name='hashed_key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['created_at']},
        ),
    ]
