# Generated by Django 5.2.11 on 2026-02-21 11:00

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_apitoken_description_apitoken_expiry_apitoken_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OIDCAPITokenIssuer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("description", models.TextField(blank=True)),
                ("issuer_uri", models.URLField(
                    validators=[django.core.validators.URLValidator(schemes=["https"])],
                    verbose_name='Issuer URI')),
                ("audience", models.TextField()),
                ("cel_condition", models.TextField(blank=True, verbose_name="CEL condition")),
                (
                    "max_validity",
                    models.IntegerField(
                        default=3600,
                        help_text="In seconds",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(604800),
                        ],
                        verbose_name="Max API token validity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
