# Generated by Django 5.2.11 on 2026-02-17 16:28

import accounts.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_apitoken_description_apitoken_expiry_apitoken_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIDCAPITokenIssuer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('issuer_uri', models.URLField(validators=[accounts.models.OIDCAPITokenIssuer._issuer_uri_validator])),
                ('audience', models.TextField()),
                ('cel_condition', models.TextField(blank=True)),
                ('max_duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
