# Generated by Django 5.2.12 on 2026-03-29 10:33

from cedarpy import format_policies
import django.core.validators
import uuid
from django.db import migrations, models


def create_policies_for_role_perms(apps, schema_editor):
    try:
        from pbac.engine import engine
    except ImportError:
        return
    Group = apps.get_model("auth", "Group")
    Policy = apps.get_model("accounts", "Policy")
    for role in Group.objects.filter(provisioned_role__provisioning_uid__isnull=True):
        policy = Policy(
            name=f"Role {role.name}",
            description=f"Policy to emulate the legacy permissions attached to the {role.name} role.",
        )
        permissions = list(role.permissions.all().order_by("content_type__app_label", "codename"))
        if not permissions:
            continue
        # legacy permission actions
        action_keys = [f"{p.content_type.app_label}.{p.codename}" for p in permissions]
        # silently skip any missing permission that might have been activated in the past
        actions = [engine.legacy_perm_actions[k] for k in action_keys if k in engine.legacy_perm_actions]
        # module level NOOP actions
        for app_label in set(perm.content_type.app_label for perm in permissions):
            noop_action = engine.module_legacy_perm_actions.get(app_label)
            # silently skip any missing app that might have been activated in the past
            if noop_action:
                actions.append(noop_action)
        serialized_actions = "\n".join(
            "     " + str(action) + ","
            for action in actions
        ).strip(",").strip()
        policy.source = format_policies(
            "permit (\n"
            f'  principal in Role::"{role.pk}",\n'
            "  action in\n"
            f"    [{serialized_actions}],\n"
            "  resource\n"
            ");"
        )
        policy.save()


def noop_reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_oidcapitokenissuer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provisioning_uid",
                    models.CharField(
                        editable=False, max_length=256, null=True, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CEDAR", "Cedar")], default="CEDAR", max_length=64
                    ),
                ),
                ("source", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_policies_for_role_perms, noop_reverse_func),
    ]
