# Generated by Django 5.2.16 on 2026-08-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcapitokenissuer',
            name='cel_condition',
            field=models.TextField(
                help_text='Only the identity tokens whose claims satisfy this expression are accepted.',
                verbose_name='CEL condition'
            ),
        ),
    ]
