# Generated by Django 3.2.18 on 2023-05-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0076_remove_currentmachinesnapshot_tree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.CharField(max_length=256, unique=True,
                                               help_text='The microsoft Azure Tenant ID')),
                ('client_id', models.UUIDField(unique=True, help_text='The client ID of your app registration')),
                ('client_secret', models.TextField(help_text='The client secret of your app registration')),
                ('version', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                    to='inventory.BusinessUnit')),
            ],
        ),
    ]
