#!/bin/sh
## postinstall

## load com.facebook.osqueryd
/bin/launchctl load -w "/Library/LaunchDaemons/com.facebook.osqueryd.plist"

## write zentral base url
/usr/bin/defaults write /Library/Preferences/io.zentral.plist base_url "https://%TLS_HOSTNAME%"

exit 0
