#!/bin/bash
# Postinstall script

ZENTRAL_OSQUERY_PLIST="/Library/LaunchDaemons/pro.zentral.osqueryd.plist"

OSQUERYD_PATH=""
for CANDIDATE_PATH in %OSQUERYD_PATHS%
do
    if [[ -x "$CANDIDATE_PATH" ]]
    then
        OSQUERYD_PATH="$CANDIDATE_PATH"
        break
    fi
done

if [[ -n "$OSQUERYD_PATH" ]]
then
    /usr/libexec/PlistBuddy -c "Set :ProgramArguments:0 $OSQUERYD_PATH" "$ZENTRAL_OSQUERY_PLIST"
fi

# load launch daemon
/bin/launchctl load -w "$ZENTRAL_OSQUERY_PLIST"

# write zentral base url
/usr/bin/defaults write /Library/Preferences/io.zentral.plist base_url "https://%TLS_HOSTNAME%"

exit 0
