#!/bin/sh
## Preinstall script

ZENTRAL_OSQUERY_ROOT="/usr/local/zentral/osquery"
OSQUERY_ROCKSDB_PATH="$ZENTRAL_OSQUERY_ROOT/db"
OSQUERY_ENROLL_SECRET_PATH="$ZENTRAL_OSQUERY_ROOT/enroll_secret.txt"

## unload com.facebook.osqueryd
/bin/launchctl unload -w "/Library/LaunchDaemons/com.facebook.osqueryd.plist"

## unload io.zentral.osquery.watchdog.plist
/bin/launchctl unload -w "/Library/LaunchDaemons/io.zentral.osquery.watchdog.plist"

# delete existing osquery DB to force enrollment
if [[ -d "$OSQUERY_ROCKSDB_PATH" ]]; then
  /bin/rm -rf "$OSQUERY_ROCKSDB_PATH"
fi

# create directory for osquery and rocksDB
/bin/mkdir -p "$OSQUERY_ROCKSDB_PATH"
/usr/sbin/chown -R root:admin "$ZENTRAL_OSQUERY_ROOT"

# create log directory for osqueryd
/bin/mkdir -p "/var/log/osquery"
/usr/sbin/chown -R root:admin "/var/log/osquery"

# create enrollment file from a secret
echo "%ENROLL_SECRET_SECRET%" > "$OSQUERY_ENROLL_SECRET_PATH"

# lock down enrollment secret file
/bin/chmod 400 "$OSQUERY_ENROLL_SECRET_PATH"
/usr/sbin/chown root:admin "$OSQUERY_ENROLL_SECRET_PATH"

exit 0
