# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedapplication',
            name='bundle_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
