# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-23 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0003_auto_20180214_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='mode',
            new_name='client_mode',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='secret',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='santa_enrollment', to='inventory.EnrollmentSecret'),
        ),
    ]
