# Generated by Django 2.1.7 on 2019-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0008_auto_20190227_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='file_changes_prefix_filters',
            field=models.TextField(blank=True, help_text='A list of ignore prefixes which are checked in-kernel. This is more performant than FileChangesRegex when ignoring whole directory trees.'),
        ),
    ]
