# Generated by Django 2.2.1 on 2019-06-03 15:43

from django.db import migrations


def update_santa_releases(apps, schema_editor):
    Enrollment = apps.get_model("santa", "Enrollment")
    for enrollment in Enrollment.objects.filter(santa_release__gt=""):
        enrollment.santa_release = enrollment.santa_release.replace("santa-", "").replace(".dmg", "")
        enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0009_configuration_file_changes_prefix_filters'),
    ]

    operations = [
        migrations.RunPython(update_santa_releases),
    ]
