# Generated by Django 2.2.10 on 2020-05-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0010_auto_20190603_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_bad_signature_protection',
            field=models.BooleanField(default=False, help_text='When enabled, a binary that is signed but has a bad signature (cert revoked, binary tampered with, etc.) will be blocked regardless of client-mode unless a binary whitelist.'),
        ),
    ]
