# Generated by Django 2.2.15 on 2020-08-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0011_configuration_enable_bad_signature_protection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='santa_release',
        ),
        migrations.AddField(
            model_name='configuration',
            name='client_auth_certificate_issuer_cn',
            field=models.CharField(blank=True, help_text='If set, this is the Issuer Name of a certificate in the System keychain to be used for sync authentication. The corresponding private key must also be in the keychain.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledmachine',
            unique_together={('enrollment', 'serial_number')},
        ),
    ]
