# Generated by Django 2.2.15 on 2020-08-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0012_auto_20200817_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='hardware_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='enrolledmachine',
            name='serial_number',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledmachine',
            unique_together={('enrollment', 'hardware_uuid')},
        ),
        migrations.RemoveField(
            model_name='enrolledmachine',
            name='machine_id',
        ),
    ]
