# Generated by Django 2.2.15 on 2020-08-17 14:26

import uuid
from django.db import migrations


def void_current_enrollments(apps, schema_editor):
    EnrolledMachine = apps.get_model("santa", "EnrolledMachine")
    for em in EnrolledMachine.objects.all():
        em.hardware_uuid = uuid.uuid4()
        em.save()


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0013_auto_20200817_1425'),
    ]

    operations = [
        migrations.RunPython(void_current_enrollments)
    ]
