# Generated by Django 2.2.15 on 2020-08-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0014_auto_20200817_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledmachine',
            name='hardware_uuid',
            field=models.UUIDField(),
        ),
    ]
