# Generated by Django 2.2.15 on 2020-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0016_auto_20200818_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='enable_bundles',
            field=models.BooleanField(default=False, help_text='If set, the bundle scanning feature is enabled.'),
        ),
    ]
