# Generated by Django 2.2.17 on 2021-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0022_auto_20210121_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='binary_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='certificate_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='compiler_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='transitive_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enrolledmachine',
            name='serial_number',
            field=models.TextField(db_index=True),
        ),
    ]
