# Generated by Django 2.2.18 on 2021-09-21 15:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0058_machine_snapshot_disks_on_delete_cascade'),
        ('santa', '0024_auto_20210211_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='excluded_primary_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='rule',
            name='excluded_serial_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='rule',
            name='excluded_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.tag'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.tag'),
        ),
    ]
