# Generated by Django 3.2.14 on 2022-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0029_rule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='sync_incident_severity',
            field=models.IntegerField(choices=[(300, 'Critical'),
                                               (200, 'Major'),
                                               (100, 'Minor'),
                                               (0, 'None')],
                                      default=0,
                                      help_text="If not 'None', incidents will be automatically opened and closed "
                                                "when the santa agent rules are out of sync."),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='last_sync_ok',
            field=models.BooleanField(null=True),
        ),
    ]
