# Generated by Django 3.2.14 on 2022-09-21 06:15

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0031_auto_20220812_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='block_usb_mass_storage',
            new_name='block_usb_mount',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='block_usb_mount',
            field=models.BooleanField(
                default=False,
                help_text='If set, USB mass storage devices will be blocked or remounted.',
                verbose_name='Block USB mount'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='remount_usb_mode',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=16, validators=[django.core.validators.MinLengthValidator(2)]
                ),
                blank=True, default=list, size=None,
                help_text='Comma separated list of mount options used to remount the USB mass storage devices. '
                          'If left empty, the devices will not be remounted. '
                          'Only available if Block USB Mount is set.',
                verbose_name='Remount USB mode'
            ),
        ),
    ]
