# Generated by Django 3.2.18 on 2023-06-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0032_auto_20220921_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='signingid_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('BINARY', 'Binary'),
                                            ('BUNDLE', 'Bundle'),
                                            ('CERTIFICATE', 'Certificate'),
                                            ('SIGNINGID', 'Signing ID'),
                                            ('TEAMID', 'Team ID')], max_length=16),
        ),
    ]
