# Generated by Django 4.2.13 on 2024-06-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0033_add_signing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='cdhash_rule_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='type',
            field=models.CharField(choices=[('BINARY', 'Binary'),
                                            ('BUNDLE', 'Bundle'),
                                            ('CDHASH', 'cdhash'),
                                            ('CERTIFICATE', 'Certificate'),
                                            ('SIGNINGID', 'Signing ID'),
                                            ('TEAMID', 'Team ID')],
                                   max_length=16),
        ),
    ]
