# Generated by Django 4.2.13 on 2024-06-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0035_target_blocked_count_target_collected_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='blocked_count',
        ),
        migrations.RemoveField(
            model_name='target',
            name='collected_count',
        ),
        migrations.RemoveField(
            model_name='target',
            name='executed_count',
        ),
        migrations.RemoveField(
            model_name='target',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='TargetCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_count', models.IntegerField(default=0)),
                ('collected_count', models.IntegerField(default=0)),
                ('executed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    to='santa.configuration')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='santa.target')),
            ],
            options={
                'unique_together': {('target', 'configuration')},
            },
        ),
    ]
