# Generated by Django 4.2.13 on 2024-06-11 13:50

from django.db import migrations


def create_all_target_counters(apps, schema_editor):
    Configuration = apps.get_model("santa", "Configuration")
    Target = apps.get_model("santa", "Target")
    TargetCounter = apps.get_model("santa", "TargetCounter")
    configurations = list(Configuration.objects.all())
    new_target_counters = []
    for target in Target.objects.all():
        for configuration in configurations:
            new_target_counters.append(TargetCounter(target=target, configuration=configuration, collected_count=1))
        if len(new_target_counters) >= 500:
            TargetCounter.objects.bulk_create(new_target_counters, ignore_conflicts=True)
            new_target_counters = []
    if new_target_counters:
        TargetCounter.objects.bulk_create(new_target_counters, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0036_remove_target_blocked_count_and_more'),
    ]

    operations = [
        migrations.RunPython(create_all_target_counters),
    ]
