# Generated by Django 4.2.23 on 2025-06-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("santa", "0038_rule_is_voting_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="cel_expr",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="machinerule",
            name="policy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Allowlist"),
                    (2, "Blocklist"),
                    (3, "Silent blocklist"),
                    (4, "Remove"),
                    (5, "Allowlist compiler"),
                    (9, "CEL"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="policy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Allowlist"),
                    (2, "Blocklist"),
                    (3, "Silent blocklist"),
                    (5, "Allowlist compiler"),
                    (9, "CEL"),
                ]
            ),
        ),
    ]
