# Generated by Django 4.2.18 on 2025-02-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("santa", "0038_rule_is_voting_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetstate",
            name="state",
            field=models.IntegerField(
                choices=[
                    (-100, "Banned"),
                    (-50, "Suspect"),
                    (0, "Untrusted"),
                    (50, "Tolerated"),
                    (100, "Allowlisted"),
                ],
                default=0,
            ),
        ),
    ]
