# Generated by Django 5.2.9 on 2026-02-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0039_rule_cel_expr_rule_notification_app_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='custom_url',
            field=models.TextField(blank=True),
        ),
    ]
