# Generated by Django 5.2.11 on 2026-02-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0040_rule_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='custom_url',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
