# Generated by Django 5.2.16 on 2026-08-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0041_alter_rule_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='last_postflight_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='last_preflight_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='sync_session',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='sync_session_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinerule',
            name='staged_removal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinerule',
            name='sync_session',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddIndex(
            model_name='enrolledmachine',
            index=models.Index(fields=['last_preflight_at'], name='santa_enrol_last_pr_62e06d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrolledmachine',
            index=models.Index(fields=['last_postflight_at'], name='santa_enrol_last_po_47f6f7_idx'),
        ),
    ]
