# Generated by Django 5.2.16 on 2026-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0041_alter_rule_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='sync_session',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='sync_session_clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinerule',
            name='staged_removal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='machinerule',
            name='sync_session',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
