# Generated by Django 5.2.16 on 2026-08-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0042_enrolledmachine_sync_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='reported_sync_incident_severity',
            field=models.IntegerField(null=True),
        ),
    ]
