# Generated by Django 5.2.17 on 2026-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0043_enrolledmachine_reported_sync_incident_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinerule',
            name='committed_policy',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Allowlist'),
                    (2, 'Blocklist'),
                    (3, 'Silent blocklist'),
                    (4, 'Remove'),
                    (5, 'Allowlist compiler'),
                    (9, 'CEL'),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='machinerule',
            name='committed_version',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
