# Generated by Django 5.2.17 on 2026-08-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0045_machinerule_staged_removal_committed_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='forced_sync_type',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('CLEAN_ALL', 'Clean all')], max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='forced_sync_type_at',
            field=models.DateTimeField(null=True),
        ),
    ]
