# Generated by Django 5.2.17 on 2026-09-12 13:05

from django.db import migrations, models


def set_voting_portal_source(apps, schema_editor):
    # Until now, a voting realm with the user portal implied the button. Only the database side of
    # that condition is tested here: the user_portal app setting is deployment specific, and
    # Configuration.get_event_detail() falls back to distributing nothing when it is off.
    Configuration = apps.get_model("santa", "Configuration")
    (Configuration.objects.filter(voting_realm__isnull=False, voting_realm__user_portal=True)
                          .update(event_detail_source="VOTING_PORTAL"))


def unset_voting_portal_source(apps, schema_editor):
    Configuration = apps.get_model("santa", "Configuration")
    Configuration.objects.filter(event_detail_source="VOTING_PORTAL").update(event_detail_source="LOCAL")


class Migration(migrations.Migration):

    dependencies = [
        ('santa', '0046_enrolledmachine_forced_sync_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='event_detail_source',
            field=models.CharField(choices=[('LOCAL', 'Local configuration'), ('VOTING_PORTAL', 'Voting portal'), ('CUSTOM', 'Custom'), ('NONE', 'None')], default='LOCAL', help_text='Where the block notification button comes from. Local configuration sends nothing, and leaves the button to the configuration profile. Switching back to it does not remove a button already sent to a machine: force a clean sync to do that.', max_length=16),
        ),
        migrations.AddField(
            model_name='configuration',
            name='event_detail_text',
            field=models.TextField(blank=True, help_text='Label of the block notification button.'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='event_detail_url',
            field=models.URLField(blank=True, help_text='Custom URL of the block notification button. The following sequences are replaced: %file_identifier%, %bundle_or_file_identifier%, %file_bundle_id%, %team_id%, %signing_id%, %cdhash%, %username%, %machine_id%, %hostname%, %uuid%, %serial%.', max_length=1024),
        ),
        migrations.RunPython(set_voting_portal_source, unset_voting_portal_source),
    ]
