# Generated by Django 5.2.17 on 2026-09-14 11:49

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_osxappinstance_cd_hash_osxappinstance_entitlements_and_more'),
        ('santa', '0047_event_detail_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopedClientMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('serial_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('excluded_serial_numbers', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('primary_users', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('excluded_primary_users', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_mode', models.IntegerField(choices=[(1, 'Monitor'), (2, 'Lockdown')])),
                ('event_detail_source', models.CharField(choices=[('INHERIT', 'Inherit'), ('VOTING_PORTAL', 'Voting portal'), ('CUSTOM', 'Custom'), ('NONE', 'None')], default='INHERIT', help_text='Where the block notification button of the machines in scope comes from. Inherit takes the one of the configuration.', max_length=16)),
                ('event_detail_url', models.URLField(blank=True, help_text='Custom URL of the block notification button. The following sequences are replaced: %file_identifier%, %bundle_or_file_identifier%, %file_bundle_id%, %team_id%, %signing_id%, %cdhash%, %username%, %machine_id%, %hostname%, %uuid%, %serial%.', max_length=1024)),
                ('event_detail_text', models.TextField(blank=True, help_text='Label of the block notification button.')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santa.configuration')),
                ('excluded_tags', models.ManyToManyField(blank=True, related_name='+', to='inventory.tag')),
                ('tags', models.ManyToManyField(blank=True, related_name='+', to='inventory.tag')),
            ],
            options={
                'unique_together': {('configuration', 'name')},
            },
        ),
    ]
