# Generated by Django 5.2.17 on 2026-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0084_osxappinstance_cd_hash_osxappinstance_entitlements_and_more'),
        ('santa', '0049_scoped_path_regex'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='scopedpathregex',
            name='regex',
            field=models.CharField(help_text='ICU pattern, matched against the path of the executable. It is anchored at the start of the path: use a leading .* to match anywhere. Capture groups are not allowed, because the entries of a policy are combined into one pattern. At most 512 characters.', max_length=512),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(fields=('configuration', 'target', 'policy'), name='santa_rule_one_per_target_and_policy'),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_voting_rule', True)), fields=('configuration', 'target'), name='santa_rule_one_voting_rule_per_target'),
        ),
        migrations.AddConstraint(
            model_name='scopedclientmode',
            constraint=models.UniqueConstraint(fields=('configuration', 'client_mode'), name='santa_scopedclientmode_one_per_mode'),
        ),
        # the composition removes a leading ^, so ^/a/ and /a/ are one pattern. The form and the
        # API remove it before the constraint is checked, and the rows written before them follow.
        migrations.RunSQL(
            sql="update santa_scopedpathregex set regex = substr(regex, 2) where regex like '^%'",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name='scopedpathregex',
            constraint=models.UniqueConstraint(fields=('configuration', 'regex', 'policy'), name='santa_scopedpathregex_one_per_pattern_and_policy'),
        ),
    ]
