# Generated by Django 2.2.1 on 2019-05-14 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_auto_20190426_1611'),
        ('filebeat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledmachine',
            name='enrollment',
        ),
        migrations.CreateModel(
            name='EnrollmentSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('SCEP_VERIFIED', 'SCEP verified'), ('COMPLETED', 'Completed')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filebeat.EnrolledMachine')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filebeat.Enrollment')),
                ('enrollment_secret', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='filebeat_enrollment_session', to='inventory.EnrollmentSecret')),
                ('scep_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.EnrollmentSecretRequest')),
            ],
        ),
    ]
