# Generated by Django 2.2.1 on 2019-05-16 09:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filebeat', '0002_auto_20190514_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='inputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
