# Generated by Django 2.2.3 on 2019-09-18 15:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebeat', '0004_auto_20190607_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='inputs',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False),
        ),
        migrations.AlterField(
            model_name='enrolledmachine',
            name='serial_number',
            field=models.TextField(unique=True),
        ),
    ]
