# Generated by Django 3.2.12 on 2022-04-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0002_instance_report_heartbeat_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='principal_user_display_name_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instance',
            name='principal_user_principal_name_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='instance',
            name='principal_user_unique_id_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
