#!/usr/local/munki/munki-python
# Thanks to Graham Gilbert for
# https://github.com/salsoftware/sal/blob/master/scripts/preflight
import sys
import os
import subprocess

PREFLIGHT_DIR = '/usr/local/munki/preflight.d'


def iter_preflight_scripts(preflight_dir):
    for script in os.listdir(preflight_dir):
        script_path = os.path.join(preflight_dir, script)
        if not os.access(script_path, os.X_OK):
            print(f"'{script_path}' is not executable or has bad permissions")
        else:
            yield script_path


def execute_preflight_scripts(preflight_dir):
    for script_path in iter_preflight_scripts(preflight_dir):
        try:
            subprocess.call([script_path, sys.argv[1]])
        except OSError:
            print(f"Could not execute script '{script_path}'!")


if __name__ == '__main__':
    execute_preflight_scripts(PREFLIGHT_DIR)
