#!/bin/bash -e
# Preinstall script

# unload launch daemon
DAEMON_PLIST="/Library/LaunchDaemons/io.zentral.audit_shipper.plist"
if [ -e "$DAEMON_PLIST" ]; then
    /bin/launchctl unload -w "$DAEMON_PLIST";
fi

exit 0
