# Generated by Django 2.2.18 on 2021-03-17 07:26

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_default_configuration(apps, schema_editor):
    try:
        from zentral.conf import settings
        from zentral.contrib.munki.models import PrincipalUserDetectionSource
        current_settings = settings['apps']['zentral.contrib.munki'].serialize()
    except Exception:
        return

    # get the current configuration from base.json
    principal_user_detection_sources = []
    principal_user_detection_domains = []
    pud_d = current_settings.get("principal_user_detection")
    if pud_d:
        principal_user_detection_sources = [
            i for i in pud_d.get("sources", [])
            if i in PrincipalUserDetectionSource.accepted_sources()
        ]
        principal_user_detection_domains = pud_d.get("domains", [])

    # save the current configuration
    Configuration = apps.get_model("munki", "Configuration")
    configuration, created = Configuration.objects.get_or_create(
        name="Default",
        inventory_apps_full_info_shard=0,
        principal_user_detection_sources=principal_user_detection_sources,
        principal_user_detection_domains=principal_user_detection_domains,
        version=1
    )

    # link the current enrollments to this configuration
    Enrollment = apps.get_model("munki", "Enrollment")
    for enrollment in Enrollment.objects.all():
        enrollment.configuration = configuration
        enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0006_remove_munkistate_binaryinfo_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('inventory_apps_full_info_shard',
                 models.IntegerField(default=100,
                                     validators=[django.core.validators.MinValueValidator(0),
                                                 django.core.validators.MaxValueValidator(100)])),
                ('principal_user_detection_sources',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.CharField(choices=[('company_portal', 'Company portal'),
                                                          ('google_chrome', 'Google Chrome'),
                                                          ('logged_in_user', 'Logged-in user')], max_length=64),
                     blank=True, default=list, size=None)
                 ),
                ('principal_user_detection_domains',
                 django.contrib.postgres.fields.ArrayField(
                     base_field=models.CharField(max_length=255),
                     blank=True, default=list, size=None)
                 ),
                ('version', models.PositiveIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='munki.Configuration'),
        ),
        migrations.RunPython(create_default_configuration),
        migrations.AlterField(
            model_name='enrollment',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munki.Configuration'),
        )
    ]
