# Generated by Django 2.2.24 on 2021-10-12 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0007_auto_20210317_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='managed_installs_sync_interval_days',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='munkistate',
            name='last_managed_installs_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='munkistate',
            name='machine_serial_number',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='ManagedInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.TextField(db_index=True)),
                ('pkg_info_name', models.TextField(db_index=True)),
                ('pkg_info_display_name', models.TextField()),
                ('pkg_info_version', models.TextField()),
                ('installed_at', models.DateTimeField(null=True)),
            ],
            options={
                'unique_together': {('machine_serial_number', 'pkg_info_name')},
            },
        ),
    ]
