# Generated by Django 2.2.24 on 2021-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0008_auto_20211012_2023'),
    ]

    operations = [
        # configuration auto incidents options
        migrations.AddField(
            model_name='configuration',
            name='auto_failed_install_incidents',
            field=models.BooleanField(
                default=False,
                help_text='Enable automatic package failed install incidents',
                verbose_name='Auto failed install incidents'
            ),
        ),
        migrations.AddField(
            model_name='configuration',
            name='auto_reinstall_incidents',
            field=models.BooleanField(
                default=False,
                help_text='Enable automatic package reinstall incidents',
                verbose_name='Auto reinstall incidents'
            ),
        ),

        # more state in managed install
        migrations.RenameField(
            model_name='managedinstall',
            old_name='pkg_info_display_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='managedinstall',
            old_name='pkg_info_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='managedinstall',
            old_name='pkg_info_version',
            new_name='installed_version',
        ),
        migrations.AlterField(
            model_name='managedinstall',
            name='installed_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='managedinstall',
            name='failed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='managedinstall',
            name='failed_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='managedinstall',
            name='reinstall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managedinstall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='managedinstall',
            unique_together={('machine_serial_number', 'name')},
        ),
    ]
