# Generated by Django 2.2.24 on 2021-12-26 13:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0009_auto_20211201_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='collected_condition_keys',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True, default=list,
                help_text='List of Munki condition keys to collect as machine extra facts', size=None
            ),
        ),
    ]
