# Generated by Django 4.2.8 on 2023-12-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_file_signing_id'),
        ('munki', '0012_script_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptcheck',
            name='excluded_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.tag'),
        ),
        migrations.AlterField(
            model_name='scriptcheck',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='inventory.tag'),
        ),
    ]
