# Generated by Django 4.2.13 on 2024-07-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0013_scriptcheck_excluded_tags_alter_scriptcheck_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='munkistate',
            name='force_full_sync_at',
            field=models.DateTimeField(null=True),
        ),
    ]
