# Generated by Django 5.2.16 on 2026-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munki', '0015_munkistate_contact_timestamps'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='munkistate',
            index=models.Index(fields=['last_preflight_at'], name='munki_ms_last_preflight_at'),
        ),
        migrations.AddIndex(
            model_name='munkistate',
            index=models.Index(fields=['last_postflight_at'], name='munki_ms_last_postflight_at'),
        ),
    ]
