computer_response = {
    "general": {
        "id": 1,
        "name": "jappleseed’s MacBook",
        "network_adapter_type": "IEEE80211",
        "mac_address": "11:6F:99:06:B2:98",
        "alt_network_adapter_type": "",
        "alt_mac_address": "",
        "ip_address": "203.0.113.10",
        "last_reported_ip": "192.168.1.10",
        "serial_number": "C094B14CDCD2",
        "udid": "54F50251-7D34-470E-98D1-E1C34A90BF60",
        "jamf_version": "10.40.1-t1659581750",
        "platform": "Mac",
        "barcode_1": "",
        "barcode_2": "",
        "asset_tag": "",
        "remote_management": {
            "managed": True,
            "management_username": "yolo",
            "management_password_sha256": "********************",
        },
        "supervised": True,
        "mdm_capable": True,
        "mdm_capable_users": {"mdm_capable_user": "jappleseed"},
        "management_status": {
            "enrolled_via_dep": False,
            "user_approved_enrollment": True,
            "user_approved_mdm": True,
        },
        "report_date": "2022-08-13 09:13:05",
        "report_date_epoch": 1660381985571,
        "report_date_utc": "2022-08-13T09:13:05.571+0000",
        "last_contact_time": "2022-08-16 01:33:23",
        "last_contact_time_epoch": 1660613603714,
        "last_contact_time_utc": "2022-08-16T01:33:23.714+0000",
        "initial_entry_date": "2022-06-23",
        "initial_entry_date_epoch": 1655992246286,
        "initial_entry_date_utc": "2022-06-23T13:50:46.286+0000",
        "last_cloud_backup_date_epoch": 0,
        "last_cloud_backup_date_utc": "",
        "last_enrolled_date_epoch": 1660381973512,
        "last_enrolled_date_utc": "2022-08-13T09:12:53.512+0000",
        "mdm_profile_expiration_epoch": 1723540337000,
        "mdm_profile_expiration_utc": "2024-08-13T09:12:17.000+0000",
        "distribution_point": "",
        "sus": "",
        "site": {"id": -1, "name": "None"},
        "itunes_store_account_is_active": False,
    },
    "location": {
        "username": "",
        "realname": "",
        "real_name": "",
        "email_address": "",
        "position": "",
        "phone": "",
        "phone_number": "",
        "department": "",
        "building": "",
        "room": "",
    },
    "purchasing": {
        "is_purchased": True,
        "is_leased": False,
        "po_number": "",
        "vendor": "",
        "applecare_id": "",
        "purchase_price": "",
        "purchasing_account": "",
        "po_date": "",
        "po_date_epoch": 0,
        "po_date_utc": "",
        "warranty_expires": "",
        "warranty_expires_epoch": 0,
        "warranty_expires_utc": "",
        "lease_expires": "",
        "lease_expires_epoch": 0,
        "lease_expires_utc": "",
        "life_expectancy": 0,
        "purchasing_contact": "",
        "os_applecare_id": "",
        "os_maintenance_expires": "",
        "attachments": [],
    },
    "peripherals": [],
    "hardware": {
        "make": "Apple",
        "model": "MacBook (12-inch Retina Early 2016)",
        "model_identifier": "MacBook9,1",
        "os_name": "macOS",
        "os_version": "12.0.1",
        "os_build": "21A559",
        "software_update_device_id": "Mac-9AE82516C7C6B903",
        "active_directory_status": "Not Bound",
        "service_pack": "",
        "processor_type": "Dual-Core Intel Core m7",
        "is_apple_silicon": False,
        "processor_architecture": "x86_64",
        "processor_speed": 1300,
        "processor_speed_mhz": 1300,
        "number_processors": 1,
        "number_cores": 2,
        "total_ram": 8192,
        "total_ram_mb": 8192,
        "boot_rom": "451.140.1.0.0",
        "bus_speed": 0,
        "bus_speed_mhz": 0,
        "battery_capacity": 87,
        "cache_size": 4096,
        "cache_size_kb": 4096,
        "available_ram_slots": 0,
        "optical_drive": "",
        "nic_speed": "n/a",
        "smc_version": "2.35f108",
        "ble_capable": False,
        "supports_ios_app_installs": False,
        "sip_status": "Enabled",
        "gatekeeper_status": "App Store and identified developers",
        "xprotect_version": "2150",
        "institutional_recovery_key": "Not Present",
        "disk_encryption_configuration": "",
        "filevault2_users": ["jappleseed"],
        "storage": [
            {
                "disk": "disk0",
                "model": "APPLE SSD AP0512J",
                "revision": "9.134.01",
                "serial_number": "4DDBE24D40BFB0419",
                "size": 500277,
                "drive_capacity_mb": 500277,
                "connection_type": "NO",
                "smart_status": "Verified",
                "partitions": [
                    {
                        "name": "VM",
                        "size": 499963,
                        "type": "other",
                        "partition_capacity_mb": 499963,
                        "percentage_full": 1,
                        "available_mb": 479642,
                        "filevault_status": "Not Encrypted",
                        "filevault_percent": 0,
                        "filevault2_status": "Not Encrypted",
                        "filevault2_percent": 0,
                    },
                    {
                        "name": "Update",
                        "size": 499963,
                        "type": "other",
                        "partition_capacity_mb": 499963,
                        "percentage_full": 1,
                        "available_mb": 479642,
                        "filevault_status": "Not Encrypted",
                        "filevault_percent": 0,
                        "filevault2_status": "Not Encrypted",
                        "filevault2_percent": 0,
                    },
                    {
                        "name": "Data",
                        "size": 499963,
                        "type": "other",
                        "partition_capacity_mb": 499963,
                        "percentage_full": 1,
                        "available_mb": 479642,
                        "filevault_status": "Not Encrypted",
                        "filevault_percent": 0,
                        "filevault2_status": "Not Encrypted",
                        "filevault2_percent": 0,
                    },
                    {
                        "name": "MacHD (Boot Partition)",
                        "size": 499963,
                        "type": "boot",
                        "partition_capacity_mb": 499963,
                        "percentage_full": 4,
                        "available_mb": 479642,
                        "filevault_status": "Not Encrypted",
                        "filevault_percent": 0,
                        "filevault2_status": "Not Encrypted",
                        "filevault2_percent": 0,
                        "boot_drive_available_mb": 479642,
                        "lvgUUID": "",
                        "lvUUID": "",
                        "pvUUID": "",
                    },
                    {
                        "name": "Preboot",
                        "size": 499963,
                        "type": "other",
                        "partition_capacity_mb": 499963,
                        "percentage_full": 1,
                        "available_mb": 479642,
                        "filevault_status": "Not Encrypted",
                        "filevault_percent": 0,
                        "filevault2_status": "Not Encrypted",
                        "filevault2_percent": 0,
                    },
                ],
            }
        ],
        "mapped_printers": [],
    },
    "certificates": [
        {
            "common_name": "YOLO JSS Built-in Certificate Authority",
            "identity": False,
            "expires_utc": "2029-02-21T18:16:03.000+0000",
            "expires_epoch": 1866392163000,
            "name": "",
        },
        {
            "common_name": "com.apple.systemdefault",
            "identity": True,
            "expires_utc": "2042-08-08T06:44:52.000+0000",
            "expires_epoch": 2291093092000,
            "name": "",
        },
        {
            "common_name": "com.apple.kerberos.kdc",
            "identity": True,
            "expires_utc": "2042-08-08T06:45:03.000+0000",
            "expires_epoch": 2291093103000,
            "name": "",
        },
        {
            "common_name": "990BF385-2569-4BEE-9A90-8B0E264AF5AE",
            "identity": True,
            "expires_utc": "2024-08-13T09:12:17.000+0000",
            "expires_epoch": 1723540337000,
            "name": "",
        },
        {
            "common_name": "com.apple.kerberos.kdc",
            "identity": True,
            "expires_utc": "2042-08-08T06:44:59.000+0000",
            "expires_epoch": 2291093099000,
            "name": "",
        },
    ],
    "security": {
        "activation_lock": False,
        "recovery_lock_enabled": False,
        "secure_boot_level": "not supported",
        "external_boot_level": "not supported",
        "firewall_enabled": False,
    },
    "software": {
        "unix_executables": [],
        "licensed_software": [],
        "installed_by_casper": [],
        "installed_by_installer_swu": [
            "com.apple.files.data-template",
            "com.jamfsoftware.osxenrollment",
        ],
        "cached_by_casper": [],
        "available_software_updates": [],
        "available_updates": {},
        "running_services": [
            "com.apple.accessoryd",
            "com.apple.AccountPolicyHelper",
            "com.apple.adid",
            "com.apple.afpfs_afpLoad",
            "com.apple.afpfs_checkafp",
            "com.apple.AirPlayXPCHelper",
            "com.apple.airport.wps",
            "com.apple.airportd",
            "com.apple.akd",
            "com.apple.alf",
            "com.apple.AmbientDisplayAgent",
            "com.apple.analyticsd",
            "com.apple.aned",
            "com.apple.apfsd",
            "com.apple.appinstalld",
            "com.apple.applecamerad",
            "com.apple.AppleCredentialManagerDaemon",
            "com.apple.applefileutil",
            "com.apple.applefsplaceholder",
            "com.apple.appleh13camerad",
            "com.apple.AppleQEMUGuestAgent",
            "com.apple.appleseed.fbahelperd",
            "com.apple.applessdstatistics",
            "com.apple.appstored",
            "com.apple.AppStoreDaemon.StorePrivilegedTaskService",
            "com.apple.apsd",
            "com.apple.aslmanager",
            "com.apple.asr",
            "com.apple.AssetCache.builtin",
            "com.apple.AssetCacheLocatorService",
            "com.apple.AssetCacheManagerService",
            "com.apple.AssetCacheTetheratorService",
            "com.apple.audio.AudioComponentRegistrar",
            "com.apple.audio.coreaudiod",
            "com.apple.audio.systemsoundserverd",
            "com.apple.audio.toolbox.reporting.service",
            "com.apple.auditd",
            "com.apple.authd",
            "com.apple.autofsd",
            "com.apple.automountd",
            "com.apple.avbdeviced",
            "com.apple.awdd",
            "com.apple.AXMediaUtilitiesService",
            "com.apple.backupd",
            "com.apple.backupd-helper",
            "com.apple.batteryintelligenced",
            "com.apple.biokitaggdd",
            "com.apple.biometrickitd",
            "com.apple.BlueTool",
            "com.apple.bluetoothd",
            "com.apple.BluetoothUIService",
            "com.apple.bnepd",
            "com.apple.bootinstalld",
            "com.apple.bosreporter",
            "com.apple.boswatcher",
            "com.apple.bridgeOSUpdateProxy",
            "com.apple.bsd.dirhelper",
            "com.apple.BTServer.le",
            "com.apple.captiveagent",
            "com.apple.cfnetwork.cfnetworkagent",
            "com.apple.cfprefsd.xpc.daemon",
            "com.apple.cloudd",
            "com.apple.cmio.AppleCameraAssistant",
            "com.apple.cmio.AVCAssistant",
            "com.apple.cmio.IIDCVideoAssistant",
            "com.apple.cmio.iOSScreenCaptureAssistant",
            "com.apple.cmio.registerassistantservice",
            "com.apple.cmio.uvcassistantextension",
            "com.apple.cmio.VDCAssistant",
            "com.apple.CodeSigningHelper",
            "com.apple.colorsync.displayservices",
            "com.apple.colorsyncd",
            "com.apple.configd",
            "com.apple.containermanagerd",
            "com.apple.contextstored",
            "com.apple.coreaudio.AudioHistoryXPC",
            "com.apple.CoreAuthentication.daemon",
            "com.apple.corebrightnessd",
            "com.apple.corecaptured",
            "com.apple.coreduetd",
            "com.apple.corekdld",
            "com.apple.coreservices.appleevents",
            "com.apple.coreservices.launchservicesd",
            "com.apple.coreservices.sharedfilelistd",
            "com.apple.coreservicesd",
            "com.apple.corestorage.corestoraged",
            "com.apple.corestorage.corestoragehelperd",
            "com.apple.coresymbolicationd",
            "com.apple.CrashReporterSupportHelper",
            "com.apple.CryptoTokenKit.ahp",
            "com.apple.CSCSupportd",
            "com.apple.csrutil.report",
            "com.apple.ctkd",
            "com.apple.cvmsServ",
            "com.apple.dasd",
            "com.apple.DataDetectorsSourceAccess",
            "com.apple.deleted_helper",
            "com.apple.DesktopServicesHelper",
            "com.apple.devicemanagementclient.teslad",
            "com.apple.diagnosticd",
            "com.apple.diagnosticextensions.osx.getmobilityinfo.helper",
            "com.apple.diagnosticextensions.osx.spotlight.helper",
            "com.apple.diagnosticextensions.osx.timemachine.helper",
            "com.apple.diagnosticextensions.osx.wifi.helper",
            "com.apple.diskarbitrationd",
            "com.apple.diskimagesiod",
            "com.apple.diskimagesiod.ram",
            "com.apple.diskimagesiod.spb",
            "com.apple.diskmanagementd",
            "com.apple.diskmanagementstartup",
            "com.apple.displaypolicyd",
            "com.apple.distnoted.xpc.daemon",
            "com.apple.dpaudiothru",
            "com.apple.dpd",
            "com.apple.dprivacyd",
            "com.apple.driver.eficheck",
            "com.apple.driver.ethcheck",
            "com.apple.dspluginhelperd",
            "com.apple.dt.automationmode-writer",
            "com.apple.DumpGPURestart",
            "com.apple.DumpPanic",
            "com.apple.dvdplayback.setregion",
            "com.apple.dynamic_pager",
            "com.apple.eapolcfg_auth",
            "com.apple.efilogin-helper",
            "com.apple.EmbeddedOSInstallService",
            "com.apple.emond",
            "com.apple.emond.aslmanager",
            "com.apple.endpointsecurity.endpointsecurityd",
            "com.apple.eoshostd",
            "com.apple.erasecontentsettingshelperd",
            "com.apple.fairplayd",
            "com.apple.familycontrols",
            "com.apple.FileCoordination",
            "com.apple.filesystems.livefileproviderd",
            "com.apple.filesystems.userfs_helper",
            "com.apple.filesystems.userfsd",
            "com.apple.findmymacd",
            "com.apple.findmymacmessenger",
            "com.apple.fontmover",
            "com.apple.fseventsd",
            "com.apple.GameController.gamecontrollerd",
            "com.apple.gkreport",
            "com.apple.GSSCred",
            "com.apple.gssd",
            "com.apple.hdiejectd",
            "com.apple.hidd",
            "com.apple.icloud.findmydeviced",
            "com.apple.icloud.searchpartyd",
            "com.apple.iconservices.iconservicesagent",
            "com.apple.iconservices.iconservicesd",
            "com.apple.IFCStart",
            "com.apple.ifdreader",
            "com.apple.installandsetup.systemmigrationd",
            "com.apple.installcoordination_proxy",
            "com.apple.installcoordinationd",
            "com.apple.installd",
            "com.apple.InstallerDiagnostics.installerdiagd",
            "com.apple.InstallerDiagnostics.installerdiagwatcher",
            "com.apple.InstallerProgress",
            "com.apple.internal.aupbregistrarservice",
            "com.apple.IOAccelMemoryInfoCollector",
            "com.apple.iokit.ioserviceauthorized",
            "com.apple.iomfb_bics_daemon",
            "com.apple.iomfb_fdr_loader",
            "com.apple.ionodecache",
            "com.apple.ioupsd",
            "com.apple.IOUserBluetoothSerialDriver-0x100000499",
            "com.apple.kcproxy",
            "com.apple.Kerberos.digest-service",
            "com.apple.Kerberos.kadmind",
            "com.apple.Kerberos.kcm",
            "com.apple.Kerberos.kdc",
            "com.apple.Kerberos.kpasswdd",
            "com.apple.KernelEventAgent",
            "com.apple.kernelmanagerd",
            "com.apple.kuncd",
            "com.apple.locationd",
            "com.apple.lockd",
            "com.apple.logd",
            "com.apple.logd_helper",
            "com.apple.logind",
            "com.apple.loginwindow",
            "com.apple.loginwindow.31AD82BA-926E-4CA7-98C6-E9738A292A28",
            "com.apple.loginwindow.8FCC4FEF-25BF-4CB7-84B1-3746547D8BB3",
            "com.apple.logkextloadsd",
            "com.apple.lsd",
            "com.apple.lskdd",
            "com.apple.ManagedClient",
            "com.apple.ManagedClient.cloudconfigurationd",
            "com.apple.ManagedClient.enroll",
            "com.apple.ManagedClient.mechanism",
            "com.apple.mbsystemadministration",
            "com.apple.mbusertrampoline",
            "com.apple.mdmclient.daemon",
            "com.apple.mdmclient.daemon.runatboot",
            "com.apple.mDNSResponder.reloaded",
            "com.apple.mDNSResponderHelper.reloaded",
            "com.apple.mediaremoted",
            "com.apple.memory-maintenance",
            "com.apple.memoryanalyticsd",
            "com.apple.metadata.mds",
            "com.apple.metadata.mds.index",
            "com.apple.metadata.mds.scan",
            "com.apple.metadata.mds.spindump",
            "com.apple.misagent",
            "com.apple.mobile.keybagd",
            "com.apple.mobile.notification_proxy",
            "com.apple.mobile.NRDUpdated",
            "com.apple.mobile.obliteration",
            "com.apple.mobile.softwareupdated",
            "com.apple.mobile.storage_mounter",
            "com.apple.mobile.storage_mounter_proxy",
            "com.apple.MobileAccessoryUpdater",
            "com.apple.mobileactivationd",
            "com.apple.mobileassetd",
            "com.apple.MobileFileIntegrity",
            "com.apple.mobilegestalt.xpc",
            "com.apple.MobileInstallationHelperService",
            "com.apple.MobileSoftwareUpdate.CleanupPreparePathService",
            "com.apple.MRTd",
            "com.apple.msrpc.lsarpc",
            "com.apple.msrpc.mdssvc",
            "com.apple.msrpc.netlogon",
            "com.apple.msrpc.srvsvc",
            "com.apple.msrpc.wkssvc",
            "com.apple.multiversed",
            "com.apple.nand.aspcarry",
            "com.apple.nehelper",
            "com.apple.nesessionmanager",
            "com.apple.netauth.sys.auth",
            "com.apple.netauth.sys.gui",
            "com.apple.netbiosd",
            "com.apple.NetworkSharing",
            "com.apple.newsyslog",
            "com.apple.nfcd",
            "com.apple.nfrestore",
            "com.apple.nfsconf",
            "com.apple.nfsd",
            "com.apple.nlcd",
            "com.apple.noticeboard.state",
            "com.apple.notifyd",
            "com.apple.nsurlsessiond_privileged",
            "com.apple.oahd",
            "com.apple.oahd-root-helper",
            "com.apple.ocspd",
            "com.apple.online-authd.xpc",
            "com.apple.opendirectoryd",
            "com.apple.osanalytics.osanalyticshelper",
            "com.apple.PerformanceTrace.PerformanceTraceService",
            "com.apple.PerfPowerServices",
            "com.apple.PerfPowerServicesExtended",
            "com.apple.periodic-daily",
            "com.apple.periodic-monthly",
            "com.apple.periodic-weekly",
            "com.apple.pfctl",
            "com.apple.pfd",
            "com.apple.postfix.master",
            "com.apple.postfix.newaliases",
            "com.apple.powerd",
            "com.apple.powerd.swd",
            "com.apple.powerdatad",
            "com.apple.powerlogHelperd",
            "com.apple.PowerUIAgent",
            "com.apple.preferences.timezone.admintool",
            "com.apple.printtool.daemon",
            "com.apple.racoon",
            "com.apple.rapportd",
            "com.apple.recoveryos-lockout-service",
            "com.apple.relatived",
            "com.apple.remoted",
            "com.apple.RemoteDesktop.PrivilegeProxy",
            "com.apple.remotemanagementd",
            "com.apple.RemotePairTool",
            "com.apple.ReportCrash.Root",
            "com.apple.ReportMemoryException",
            "com.apple.revisiond",
            "com.apple.RFBEventHelper",
            "com.apple.rpcbind",
            "com.apple.rtcreportingd",
            "com.apple.runningboardd",
            "com.apple.SafeEjectGPUStartupDaemon",
            "com.apple.sandboxd",
            "com.apple.SCHelper",
            "com.apple.scsid",
            "com.apple.secinitd",
            "com.apple.security.agent.login",
            "com.apple.security.agent.login.00000000-0000-0000-0000-0000000186A3",
            "com.apple.security.agent.login.00000000-0000-0000-0000-0000000186D9",
            "com.apple.security.authhost",
            "com.apple.security.authhost.00000000-0000-0000-0000-0000000186A3",
            "com.apple.security.authhost.00000000-0000-0000-0000-0000000186D9",
            "com.apple.security.authtrampoline",
            "com.apple.security.syspolicy",
            "com.apple.securityd",
            "com.apple.securityd_service",
            "com.apple.seld",
            "com.apple.sessionlogoutd",
            "com.apple.signpost.signpost_reporter",
            "com.apple.siri.acousticsignature",
            "com.apple.siriinferenced",
            "com.apple.smb.preferences",
            "com.apple.softwareupdated",
            "com.apple.spindump",
            "com.apple.startupdiskhelper",
            "com.apple.statd.notify",
            "com.apple.storagekitd",
            "com.apple.storereceiptinstaller",
            "com.apple.SubmitDiagInfo",
            "com.apple.suhelperd",
            "com.apple.symptomsd",
            "com.apple.symptomsd-diag",
            "com.apple.sysdiagnose",
            "com.apple.sysdiagnose_helper",
            "com.apple.sysextd",
            "com.apple.syslogd",
            "com.apple.sysmond",
            "com.apple.system_installd",
            "com.apple.systemadministration.writeconfig",
            "com.apple.systemkeychain",
            "com.apple.systempreferences.cacheAssistant",
            "com.apple.systemstats.analysis",
            "com.apple.systemstats.daily",
            "com.apple.systemstats.microstackshot_periodic",
            "com.apple.systemstatusd",
            "com.apple.tailspind",
            "com.apple.taskgated",
            "com.apple.taskgated-helper",
            "com.apple.tccd.system",
            "com.apple.thermald",
            "com.apple.thermalmonitord",
            "com.apple.timed",
            "com.apple.timezoneupdates.tzd",
            "com.apple.touchbarserver",
            "com.apple.tracd",
            "com.apple.trustd",
            "com.apple.trustdFileHelper",
            "com.apple.TrustEvaluationAgent.system",
            "com.apple.tzlinkd",
            "com.apple.ucupdate.plist",
            "com.apple.uninstalld",
            "com.apple.unmountassistant.sysagent",
            "com.apple.UpdateSettings",
            "com.apple.usbd",
            "com.apple.usbmuxd",
            "com.apple.UserEventAgent-System",
            "com.apple.UserNotificationCenter",
            "com.apple.vsdbutil",
            "com.apple.warmd",
            "com.apple.watchdogd",
            "com.apple.wifianalyticsd",
            "com.apple.wifiFirmwareLoader",
            "com.apple.wifip2pd",
            "com.apple.wifivelocityd",
            "com.apple.WindowServer",
            "com.apple.WirelessRadioManager",
            "com.apple.wwand",
            "com.apple.xartstorageremoted",
            "com.apple.xpc.roleaccountd",
            "com.apple.xpc.smd",
            "com.apple.xpc.uscwoap",
            "com.openssh.sshd",
            "com.vix.cron",
            "org.cups.cupsd",
        ],
        "applications": [
            {
                "name": "Activity Monitor.app",
                "path": "/System/Applications/Utilities/Activity Monitor.app",
                "version": "10.14",
                "bundle_id": "com.apple.ActivityMonitor",
            },
            {
                "name": "AirPort Utility.app",
                "path": "/System/Applications/Utilities/AirPort Utility.app",
                "version": "6.3.9",
                "bundle_id": "com.apple.airport.airportutility",
            },
            {
                "name": "App Store.app",
                "path": "/System/Applications/App Store.app",
                "version": "3.0",
                "bundle_id": "com.apple.AppStore",
            },
            {
                "name": "Audio MIDI Setup.app",
                "path": "/System/Applications/Utilities/Audio MIDI Setup.app",
                "version": "3.5",
                "bundle_id": "com.apple.audio.AudioMIDISetup",
            },
            {
                "name": "Automator.app",
                "path": "/System/Applications/Automator.app",
                "version": "2.10",
                "bundle_id": "com.apple.Automator",
            },
            {
                "name": "Bluetooth File Exchange.app",
                "path": "/System/Applications/Utilities/Bluetooth File Exchange.app",
                "version": "9.0",
                "bundle_id": "com.apple.BluetoothFileExchange",
            },
            {
                "name": "Books.app",
                "path": "/System/Applications/Books.app",
                "version": "4.1",
                "bundle_id": "com.apple.iBooksX",
            },
            {
                "name": "Boot Camp Assistant.app",
                "path": "/System/Applications/Utilities/Boot Camp Assistant.app",
                "version": "6.1.0",
                "bundle_id": "com.apple.bootcampassistant",
            },
            {
                "name": "Calculator.app",
                "path": "/System/Applications/Calculator.app",
                "version": "10.16",
                "bundle_id": "com.apple.calculator",
            },
            {
                "name": "Calendar.app",
                "path": "/System/Applications/Calendar.app",
                "version": "11.0",
                "bundle_id": "com.apple.iCal",
            },
            {
                "name": "Chess.app",
                "path": "/System/Applications/Chess.app",
                "version": "3.18",
                "bundle_id": "com.apple.Chess",
            },
            {
                "name": "ColorSync Utility.app",
                "path": "/System/Applications/Utilities/ColorSync Utility.app",
                "version": "12.0.0",
                "bundle_id": "com.apple.ColorSyncUtility",
            },
            {
                "name": "Console.app",
                "path": "/System/Applications/Utilities/Console.app",
                "version": "1.1",
                "bundle_id": "com.apple.Console",
            },
            {
                "name": "Contacts.app",
                "path": "/System/Applications/Contacts.app",
                "version": "2496.2",
                "bundle_id": "com.apple.AddressBook",
            },
            {
                "name": "Dictionary.app",
                "path": "/System/Applications/Dictionary.app",
                "version": "2.3.0",
                "bundle_id": "com.apple.Dictionary",
            },
            {
                "name": "Digital Color Meter.app",
                "path": "/System/Applications/Utilities/Digital Color Meter.app",
                "version": "5.22",
                "bundle_id": "com.apple.DigitalColorMeter",
            },
            {
                "name": "Disk Utility.app",
                "path": "/System/Applications/Utilities/Disk Utility.app",
                "version": "21.0",
                "bundle_id": "com.apple.DiskUtility",
            },
            {
                "name": "FaceTime.app",
                "path": "/System/Applications/FaceTime.app",
                "version": "5.0",
                "bundle_id": "com.apple.FaceTime",
            },
            {
                "name": "FindMy.app",
                "path": "/System/Applications/FindMy.app",
                "version": "3.0",
                "bundle_id": "com.apple.findmy",
            },
            {
                "name": "Font Book.app",
                "path": "/System/Applications/Font Book.app",
                "version": "10.0",
                "bundle_id": "com.apple.FontBook",
            },
            {
                "name": "Grapher.app",
                "path": "/System/Applications/Utilities/Grapher.app",
                "version": "2.7",
                "bundle_id": "com.apple.grapher",
            },
            {
                "name": "Home.app",
                "path": "/System/Applications/Home.app",
                "version": "6.0",
                "bundle_id": "com.apple.Home",
            },
            {
                "name": "Image Capture.app",
                "path": "/System/Applications/Image Capture.app",
                "version": "8.0",
                "bundle_id": "com.apple.Image_Capture",
            },
            {
                "name": "Keychain Access.app",
                "path": "/System/Applications/Utilities/Keychain Access.app",
                "version": "11.0",
                "bundle_id": "com.apple.keychainaccess",
            },
            {
                "name": "Launchpad.app",
                "path": "/System/Applications/Launchpad.app",
                "version": "1.0",
                "bundle_id": "com.apple.launchpad.launcher",
            },
            {
                "name": "Mail.app",
                "path": "/System/Applications/Mail.app",
                "version": "15.0",
                "bundle_id": "com.apple.mail",
            },
            {
                "name": "Maps.app",
                "path": "/System/Applications/Maps.app",
                "version": "3.0",
                "bundle_id": "com.apple.Maps",
            },
            {
                "name": "Messages.app",
                "path": "/System/Applications/Messages.app",
                "version": "14.0",
                "bundle_id": "com.apple.MobileSMS",
            },
            {
                "name": "Migration Assistant.app",
                "path": "/System/Applications/Utilities/Migration Assistant.app",
                "version": "12.0",
                "bundle_id": "com.apple.MigrateAssistant",
            },
            {
                "name": "Mission Control.app",
                "path": "/System/Applications/Mission Control.app",
                "version": "1.2",
                "bundle_id": "com.apple.exposelauncher",
            },
            {
                "name": "Music.app",
                "path": "/System/Applications/Music.app",
                "version": "1.2",
                "bundle_id": "com.apple.Music",
            },
            {
                "name": "News.app",
                "path": "/System/Applications/News.app",
                "version": "7.1",
                "bundle_id": "com.apple.news",
            },
            {
                "name": "Notes.app",
                "path": "/System/Applications/Notes.app",
                "version": "4.9",
                "bundle_id": "com.apple.Notes",
            },
            {
                "name": "Photo Booth.app",
                "path": "/System/Applications/Photo Booth.app",
                "version": "12.0",
                "bundle_id": "com.apple.PhotoBooth",
            },
            {
                "name": "Photos.app",
                "path": "/System/Applications/Photos.app",
                "version": "7.0",
                "bundle_id": "com.apple.Photos",
            },
            {
                "name": "Podcasts.app",
                "path": "/System/Applications/Podcasts.app",
                "version": "1.1.0",
                "bundle_id": "com.apple.podcasts",
            },
            {
                "name": "Preview.app",
                "path": "/System/Applications/Preview.app",
                "version": "11.0",
                "bundle_id": "com.apple.Preview",
            },
            {
                "name": "QuickTime Player.app",
                "path": "/System/Applications/QuickTime Player.app",
                "version": "10.5",
                "bundle_id": "com.apple.QuickTimePlayerX",
            },
            {
                "name": "Reminders.app",
                "path": "/System/Applications/Reminders.app",
                "version": "7.0",
                "bundle_id": "com.apple.reminders",
            },
            {
                "name": "Safari.app",
                "path": "/Applications/Safari.app",
                "version": "15.1",
                "bundle_id": "com.apple.Safari",
            },
            {
                "name": "Screenshot.app",
                "path": "/System/Applications/Utilities/Screenshot.app",
                "version": "1.0",
                "bundle_id": "com.apple.screenshot.launcher",
            },
            {
                "name": "Script Editor.app",
                "path": "/System/Applications/Utilities/Script Editor.app",
                "version": "2.11",
                "bundle_id": "com.apple.ScriptEditor2",
            },
            {
                "name": "Shortcuts.app",
                "path": "/System/Applications/Shortcuts.app",
                "version": "5.0",
                "bundle_id": "com.apple.shortcuts",
            },
            {
                "name": "Siri.app",
                "path": "/System/Applications/Siri.app",
                "version": "1.0",
                "bundle_id": "com.apple.siri.launcher",
            },
            {
                "name": "Stickies.app",
                "path": "/System/Applications/Stickies.app",
                "version": "10.2",
                "bundle_id": "com.apple.Stickies",
            },
            {
                "name": "Stocks.app",
                "path": "/System/Applications/Stocks.app",
                "version": "4.1",
                "bundle_id": "com.apple.stocks",
            },
            {
                "name": "System Information.app",
                "path": "/System/Applications/Utilities/System Information.app",
                "version": "11.0",
                "bundle_id": "com.apple.SystemProfiler",
            },
            {
                "name": "System Preferences.app",
                "path": "/System/Applications/System Preferences.app",
                "version": "15.0",
                "bundle_id": "com.apple.systempreferences",
            },
            {
                "name": "Terminal.app",
                "path": "/System/Applications/Utilities/Terminal.app",
                "version": "2.12",
                "bundle_id": "com.apple.Terminal",
            },
            {
                "name": "TextEdit.app",
                "path": "/System/Applications/TextEdit.app",
                "version": "1.17",
                "bundle_id": "com.apple.TextEdit",
            },
            {
                "name": "Time Machine.app",
                "path": "/System/Applications/Time Machine.app",
                "version": "1.3",
                "bundle_id": "com.apple.backup.launcher",
            },
            {
                "name": "TV.app",
                "path": "/System/Applications/TV.app",
                "version": "1.2",
                "bundle_id": "com.apple.TV",
            },
            {
                "name": "VoiceMemos.app",
                "path": "/System/Applications/VoiceMemos.app",
                "version": "2.3",
                "bundle_id": "com.apple.VoiceMemos",
            },
            {
                "name": "VoiceOver Utility.app",
                "path": "/System/Applications/Utilities/VoiceOver Utility.app",
                "version": "10",
                "bundle_id": "com.apple.VoiceOverUtility",
            },
        ],
        "fonts": [],
        "plugins": [],
    },
    "extension_attributes": [
        {
            "id": 68,
            "name": "Bootstrap",
            "type": "String",
            "multi_value": False,
            "value": "NO",
        },
        {
            "id": 70,
            "name": "Computer Sleep",
            "type": "Number",
            "multi_value": False,
            "value": "1",
        },
        {
            "id": 62,
            "name": "Location Service Active",
            "type": "String",
            "multi_value": False,
            "value": "Enabled",
        },
    ],
    "groups_accounts": {
        "computer_group_memberships": [
            "All Managed Clients",
            "All - Mac without Bootstrap",
        ],
        "local_accounts": [
            {
                "name": "jappleseed",
                "realname": "jappleseed",
                "uid": "501",
                "home": "/Users/jappleseed",
                "home_size": "-1MB",
                "home_size_mb": -1,
                "administrator": True,
                "filevault_enabled": True,
            }
        ],
        "user_inventories": {
            "disable_automatic_login": True,
            "user": {
                "username": "jappleseed",
                "password_history_depth": "",
                "password_min_length": "4",
                "password_max_age": "",
                "password_min_complex_characters": "",
                "password_require_alphanumeric": "false",
            },
        },
    },
    "iphones": [],
    "configuration_profiles": [
        {"id": 224, "name": "", "uuid": "", "is_removable": False},
        {"id": -27, "name": "", "uuid": "", "is_removable": False},
        {"id": 234, "name": "", "uuid": "", "is_removable": False},
        {"id": -1, "name": "", "uuid": "", "is_removable": False},
        {"id": -1, "name": "", "uuid": "", "is_removable": False},
        {"id": -1, "name": "", "uuid": "", "is_removable": False},
        {"id": -1, "name": "", "uuid": "", "is_removable": False},
        {"id": -1, "name": "", "uuid": "", "is_removable": False},
        {"id": 225, "name": "", "uuid": "", "is_removable": False},
        {"id": 140, "name": "", "uuid": "", "is_removable": False},
        {"id": 237, "name": "", "uuid": "", "is_removable": False},
        {"id": 239, "name": "", "uuid": "", "is_removable": False},
    ],
}

mobile_device_response = {
    "general": {
        "id": 2,
        "display_name": "ProPad",
        "device_name": "ProPad",
        "name": "ProPad",
        "asset_tag": "",
        "last_inventory_update": "Wednesday, August 17 2022 at 7:38 PM",
        "last_inventory_update_epoch": 1660765089308,
        "last_inventory_update_utc": "2022-08-17T19:38:09.308+0000",
        "capacity": 524288,
        "capacity_mb": 524288,
        "available": 441485,
        "available_mb": 441485,
        "percentage_used": 15,
        "os_type": "iOS",
        "os_version": "15.5",
        "os_build": "19F77",
        "software_update_device_id": "iPad8,10",
        "serial_number": "3EC0CCE031CC",
        "udid": "0000001-0000000000000001",
        "initial_entry_date_epoch": 1625674498375,
        "initial_entry_date_utc": "2021-07-07T16:14:58.375+0000",
        "phone_number": "",
        "ip_address": "84.158.174.21",
        "wifi_mac_address": "'D5:BE:B0:ED:3B:FB",
        "bluetooth_mac_address": "CA:C0:8F:22:2E:78",
        "modem_firmware": "3.03.03",
        "model": "iPad Pro (11-inch Cellular) (2nd Generation)",
        "model_identifier": "iPad8,10",
        "model_number": "MXE62FD",
        "modelDisplay": "iPad Pro (11-inch Cellular) (2nd Generation)",
        "model_display": "iPad Pro (11-inch Cellular) (2nd Generation)",
        "device_ownership_level": "Institutional",
        "enrollment_method": "User-initiated - no invitation",
        "last_enrollment_epoch": 1625674566977,
        "last_enrollment_utc": "2021-07-07T16:16:06.977+0000",
        "mdm_profile_expiration_epoch": 1688746566000,
        "mdm_profile_expiration_utc": "2023-07-07T16:16:06.000+0000",
        "managed": True,
        "supervised": False,
        "exchange_activesync_device_identifier": "AEA34B04E94DAD2E0BA4B010AB",
        "shared": "No",
        "diagnostic_submission": "Not Enabled",
        "app_analytics": "Not Enabled",
        "tethered": "",
        "battery_level": 19,
        "ble_capable": True,
        "device_locator_service_enabled": True,
        "do_not_disturb_enabled": True,
        "cloud_backup_enabled": True,
        "last_cloud_backup_date_epoch": 1660458606000,
        "last_cloud_backup_date_utc": "2022-08-14T06:30:06.000+0000",
        "location_services_enabled": False,
        "itunes_store_account_is_active": True,
        "last_backup_time_epoch": 0,
        "last_backup_time_utc": "",
        "site": {"id": -1, "name": "None"},
    },
    "location": {
        "username": "jappleseed@zentral.io",
        "realname": "Johnny Appleseed",
        "real_name": "Johnny Appleseed",
        "email_address": "jappleseed@zentral.io",
        "position": "",
        "phone": "",
        "phone_number": "",
        "department": "",
        "building": "",
        "room": "",
    },
    "purchasing": {
        "is_purchased": True,
        "is_leased": False,
        "po_number": "",
        "vendor": "",
        "applecare_id": "",
        "purchase_price": "",
        "purchasing_account": "",
        "po_date": "",
        "po_date_epoch": 0,
        "po_date_utc": "",
        "warranty_expires": "",
        "warranty_expires_epoch": 0,
        "warranty_expires_utc": "",
        "lease_expires": "",
        "lease_expires_epoch": 0,
        "lease_expires_utc": "",
        "life_expectancy": 0,
        "purchasing_contact": "",
        "attachments": [],
    },
    "applications": [
        {
            "application_name": "Chrome",
            "application_version": "104.0.5112.88",
            "application_short_version": "104.5112.88",
            "application_status": "Unmanaged",
            "identifier": "com.google.chrome.ios",
        },
        {
            "application_name": "Developer",
            "application_version": "1004.1.2",
            "application_short_version": "10.0.4",
            "application_status": "Unmanaged",
            "identifier": "developer.apple.wwdc-Release",
        },
        {
            "application_name": "Excel",
            "application_version": "2.63.22071504",
            "application_short_version": "2.63.2",
            "application_status": "Unmanaged",
            "identifier": "com.microsoft.Office.Excel",
        },
        {
            "application_name": "GitHub",
            "application_version": "74357630",
            "application_short_version": "1.74.0",
            "application_status": "Unmanaged",
            "identifier": "com.github.stormbreaker.prod",
        },
    ],
    "security": {
        "data_protection": True,
        "block_level_encryption_capable": True,
        "file_level_encryption_capable": True,
        "passcode_present": True,
        "passcode_compliant": True,
        "passcode_compliant_with_profile": True,
        "passcode_lock_grace_period_enforced": "Immediate",
        "hardware_encryption": 3,
        "activation_lock_enabled": True,
        "jailbreak_detected": "Normal",
    },
    "network": {
        "home_carrier_network": "iPad",
        "cellular_technology": "GSM",
        "voice_roaming_enabled": "No",
        "imei": "45 718686 566485 3",
        "iccid": "8934 5610 1630 1496 0612",
        "meid": "",
        "current_carrier_network": "iPad",
        "carrier_settings_version": "50.0",
        "current_mobile_country_code": "65535",
        "current_mobile_network_code": "65535",
        "home_mobile_country_code": "102",
        "home_mobile_network_code": "02",
        "data_roaming_enabled": True,
        "roaming": False,
        "phone_number": "",
    },
    "certificates": [
        {
            "common_name": "79813BF1-EBC5-4ADC-A7D2-2F29761C9CE2",
            "identity": True,
            "expires_utc": "2023-07-07T16:16:06.000+0000",
            "expires_epoch": "1688746566000",
        },
        {
            "common_name": "YOLO JSS Built-in Certificate Authority",
            "identity": False,
            "expires_utc": "2029-02-21T18:16:03.000+0000",
            "expires_epoch": "1866392163000",
        },
    ],
    "configuration_profiles": [
        {
            "display_name": "MDM Profile",
            "version": "1",
            "identifier": "3A6A0209-49D0-4D90-A196-1ADC25F7EE37",
            "uuid": "07844725-4212-4FD3-8BF6-C70AA1B6851C",
        }
    ],
    "provisioning_profiles": [],
    "mobile_device_groups": [
        {"id": 1, "name": "All Managed iPads"},
    ],
    "extension_attributes": [
        {
            "id": 4,
            "name": "Office",
            "type": "String",
            "multi_value": False,
            "value": "",
        },
    ],
}
