# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('osquery', '0002_delete_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedquery',
            name='meta_business_unit',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    to='inventory.MetaBusinessUnit'),
        ),
        migrations.AddField(
            model_name='distributedquery',
            name='shard',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
