# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160505_0639'),
        ('osquery', '0003_auto_20160207_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedquery',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tag'),
        ),
    ]
