# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0004_distributedquery_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributedquery',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.Tag'),
        ),
    ]
