# Generated by Django 2.2.3 on 2019-09-25 19:34

from django.db import migrations


def update_enrollment_osquery_release(apps, schema_editor):
    Enrollment = apps.get_model("osquery", "Enrollment")
    for enrollment in Enrollment.objects.filter(osquery_release__gt=""):
        enrollment.osquery_release = enrollment.osquery_release.replace("osquery-", "").replace(".pkg", "")
        enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0005_auto_20190227_1132'),
    ]

    operations = [
        migrations.RunPython(update_enrollment_osquery_release),
    ]
