# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0007_auto_20161105_1647'),
        ('osquery', '0005_auto_20160512_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedQueryProbeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial_number', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('probe_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='probes.ProbeSource')),
            ],
        ),
    ]
