# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0007_auto_20161111_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributedquery',
            name='meta_business_unit',
        ),
        migrations.RemoveField(
            model_name='distributedquery',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='distributedquerynode',
            name='distributed_query',
        ),
        migrations.DeleteModel(
            name='DistributedQuery',
        ),
        migrations.DeleteModel(
            name='DistributedQueryNode',
        ),
    ]
