# Generated by Django 2.2.18 on 2021-04-15 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0008_auto_20210323_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packquery',
            name='interval',
            field=models.IntegerField(help_text='interval in seconds to run the query (subject to splay/smoothing)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
