# Generated by Django 2.2.24 on 2021-06-29 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0009_auto_20210415_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packquery',
            name='interval',
            field=models.IntegerField(help_text='interval in seconds to run the query (subject to splay/smoothing)', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(604800)]),
        ),
    ]
