# Generated by Django 3.2.12 on 2022-03-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0011_query_compliance_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Osquery options'),
        ),
        migrations.AlterField(
            model_name='distributedqueryresult',
            name='row',
            field=models.JSONField(),
        ),
    ]
