# Generated by Django 2.2.27 on 2022-03-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0012_auto_20220329_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='event_routing_key',
            field=models.SlugField(blank=True),
        ),
    ]
