# Generated by Django 3.2.12 on 2022-04-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0013_auto_20220328_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='inventory_ec2',
            field=models.BooleanField(
                default=False,
                help_text='Include AWS EC2 information in the inventory',
                verbose_name="Inventory EC2 information"
            ),
        ),
    ]
