# Generated by Django 3.2.13 on 2022-06-10 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0014_configuration_inventory_ec2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecarvingsession',
            name='paths',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='filecarvingsession',
            name='carve_guid',
            field=models.UUIDField(unique=True),
        ),
    ]
