# Generated by Django 3.2.13 on 2022-06-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0015_auto_20220610_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='inventory_apps',
            field=models.BooleanField(
                default=False,
                help_text='Include executables (apps/programs) or linux packages in the inventory'
            ),
        ),
    ]
