# Generated by Django 3.2.14 on 2023-03-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0016_alter_configuration_inventory_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedquerymachine',
            name='memory',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distributedquerymachine',
            name='system_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distributedquerymachine',
            name='user_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distributedquerymachine',
            name='wall_time_ms',
            field=models.BigIntegerField(null=True),
        ),
    ]
