# Generated by Django 3.2.18 on 2023-06-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0017_auto_20230315_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packquery',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='osquery.query'),
        ),
    ]
