# Generated by Django 4.1.9 on 2023-10-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0077_file_signing_id'),
        ('osquery', '0018_alter_packquery_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='tag',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='inventory.tag'),
        ),
    ]
