# Generated by Django 4.1.12 on 2023-11-14 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osquery', '0019_query_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='inventory_interval',
            field=models.IntegerField(default=86400, help_text='Inventory refresh interval in seconds (Minimum: 300s)', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(172800)]),
        ),
    ]
