# Generated by Django 4.2.23 on 2025-08-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0078_file_cdhash"),
        ("osquery", "0020_alter_configuration_inventory_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurationpack",
            name="excluded_tags",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="inventory.tag"
            ),
        ),
        migrations.AlterField(
            model_name="configurationpack",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="inventory.tag"
            ),
        ),
    ]
