# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkginfo',
            name='requires',
            field=models.ManyToManyField(related_name='_pkginfo_requires_+', to='monolith.PkgInfoName'),
        ),
        migrations.AddField(
            model_name='pkginfo',
            name='update_for',
            field=models.ManyToManyField(related_name='_pkginfo_update_for_+', to='monolith.PkgInfoName'),
        ),
    ]
