# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0002_auto_20160223_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='pkginfo',
            name='version',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pkginfo',
            unique_together=set([('name', 'version')]),
        ),
    ]
