# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0003_auto_20160223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkginfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monolith.PkgInfoCategory'),
        ),
    ]
