# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0004_auto_20160223_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubManifestPkgInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('managed_installs', 'Managed Installs'), ('managed_uninstalls', 'Managed Uninstalls'), ('optional_installs', 'Optional Installs'), ('managed_updates', 'Managed Updates')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pkg_info_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='pkginfo',
            options={'ordering': ('name', 'version')},
        ),
        migrations.AlterModelOptions(
            name='pkginfoname',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='submanifest',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='submanifest',
            name='managed_installs',
        ),
        migrations.RemoveField(
            model_name='submanifest',
            name='managed_uninstalls',
        ),
        migrations.RemoveField(
            model_name='submanifest',
            name='managed_updates',
        ),
        migrations.RemoveField(
            model_name='submanifest',
            name='optional_installs',
        ),
        migrations.AddField(
            model_name='submanifestpkginfo',
            name='pkg_info_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.PkgInfoName'),
        ),
        migrations.AddField(
            model_name='submanifestpkginfo',
            name='sub_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.SubManifest'),
        ),
    ]
