# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0005_auto_20160224_0900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submanifestpkginfo',
            unique_together=set([('sub_manifest', 'pkg_info_name')]),
        ),
    ]
