# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0006_auto_20160224_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifest',
            options={'ordering': ('meta_business_unit__name',)},
        ),
        migrations.AddField(
            model_name='manifest',
            name='zentral_osquery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manifest',
            name='zentral_santa',
            field=models.BooleanField(default=False),
        ),
    ]
