# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20160505_0639'),
        ('monolith', '0007_auto_20160224_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.Catalog')),
            ],
        ),
        migrations.CreateModel(
            name='ManifestSubManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='catalogs',
        ),
        migrations.RemoveField(
            model_name='manifest',
            name='sub_manifests',
        ),
        migrations.AddField(
            model_name='manifestsubmanifest',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.Manifest'),
        ),
        migrations.AddField(
            model_name='manifestsubmanifest',
            name='sub_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.SubManifest'),
        ),
        migrations.AddField(
            model_name='manifestsubmanifest',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tag'),
        ),
        migrations.AddField(
            model_name='manifestcatalog',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.Manifest'),
        ),
        migrations.AddField(
            model_name='manifestcatalog',
            name='tags',
            field=models.ManyToManyField(to='inventory.Tag'),
        ),
    ]
