# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0008_add_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='meta_business_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.MetaBusinessUnit', unique=True),
        ),
    ]
