# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0009_auto_20160505_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='meta_business_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.MetaBusinessUnit'),
        ),
    ]
