# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0010_auto_20160505_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubManifestConfigurationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('managed_installs', 'Managed Installs'), ('managed_uninstalls', 'Managed Uninstalls'), ('optional_installs', 'Optional Installs'), ('managed_updates', 'Managed Updates')], max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('configuration_profile', models.FileField(upload_to="/tmp")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.SubManifest')),
            ],
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('-archived_at', '-priority', 'name')},
        ),
        migrations.AlterModelOptions(
            name='manifestcatalog',
            options={'ordering': ('-catalog__priority', '-catalog__name')},
        ),
        migrations.AlterUniqueTogether(
            name='submanifestconfigurationprofile',
            unique_together=set([('sub_manifest', 'name', 'version')]),
        ),
    ]
