# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0011_auto_20160820_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanifestconfigurationprofile',
            name='pkg_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
