# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0012_submanifestconfigurationprofile_pkg_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanifestconfigurationprofile',
            name='trashed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
