# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0013_auto_20160821_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanifestconfigurationprofile',
            name='identifier',
            field=models.TextField(default="_MIGRATION_DEFAULT_"),
            preserve_default=False,
        ),
    ]
