# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0014_submanifestconfigurationprofile_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='mbu_catalog',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
