# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0016_auto_20160825_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
