# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 10:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import zentral.contrib.monolith.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_machinesnapshotcommit_last_seen'),
        ('monolith', '0019_auto_20170331_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestEnrollmentPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(max_length=256)),
                ('build_kwargs', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='builder parameters')),
                ('file', models.FileField(blank=True, upload_to=zentral.contrib.monolith.models.enrollment_package_path)),
                ('pkg_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.Manifest')),
                ('tags', models.ManyToManyField(to='inventory.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='submanifestattachment',
            name='type',
            field=models.CharField(choices=[('configuration_profile', 'configuration profile'), ('package', 'package'), ('script', 'script')], max_length=32),
        ),
    ]
