# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 11:45
from __future__ import unicode_literals

from django.db import migrations
from zentral.contrib.monolith.conf import monolith_conf
from zentral.contrib.monolith.models import ManifestEnrollmentPackage
from zentral.contrib.monolith.utils import build_manifest_enrollment_package


def create_manifest_enrollment_packages(apps, schema_editor):
    pass


def build_manifest_enrollment_packages(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0020_auto_20170409_1014'),
    ]

    operations = [
        migrations.RunPython(create_manifest_enrollment_packages),
        migrations.RunPython(build_manifest_enrollment_packages),
    ]
