# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0023_auto_20170529_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('public_ip_address', models.GenericIPAddressField()),
                ('base_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monolith.Manifest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cacheserver',
            unique_together=set([('name', 'manifest')]),
        ),
    ]
