# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import zentral.contrib.monolith.models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0025_auto_20170919_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerppd',
            name='file',
            field=models.FileField(blank=True, upload_to=zentral.contrib.monolith.models.ppd_path),
        ),
    ]
