# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0026_auto_20170919_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerppd',
            name='pc_file_name',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
