# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0028_auto_20170919_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printer',
            name='info',
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(help_text='display name of the printer', max_length=128),
        ),
    ]
