# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0029_auto_20170919_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='trashed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
