# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0031_auto_20170920_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='scheme',
            field=models.CharField(choices=[('ipp', 'ipp'), ('ipps', 'ipps'), ('http', 'http'), ('https', 'https'), ('lpd', 'lpd'), ('socket', 'socket')], default='ipp', max_length=5),
        ),
    ]
