# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-22 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0032_auto_20180411_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifestenrollmentpackage',
            name='build_kwargs',
        ),
        migrations.AddField(
            model_name='manifestenrollmentpackage',
            name='enrollment_pk',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
