# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0034_auto_20180530_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('predicate', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='submanifestattachment',
            name='featured_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submanifestpkginfo',
            name='featured_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submanifestattachment',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monolith.Condition'),
        ),
        migrations.AddField(
            model_name='submanifestpkginfo',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monolith.Condition'),
        ),
    ]
