# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_auto_20180918_1211'),
        ('monolith', '0035_auto_20180903_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='taxonomies',
            field=models.ManyToManyField(to='inventory.Taxonomy'),
        ),
    ]
