# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-19 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0036_enrollment_taxonomies'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmachine',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrolledmachine',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, help_text='The user will be asked to pick a tag of each one of the selected taxonomies during the enrollment.', to='inventory.Taxonomy'),
        ),
    ]
