# Generated by Django 2.1.7 on 2019-02-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0037_auto_20180919_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monolith.Configuration'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='distributor_content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='meta_business_unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='manifestcatalog',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monolith.Catalog'),
        ),
        migrations.AlterField(
            model_name='manifestsubmanifest',
            name='sub_manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monolith.SubManifest'),
        ),
        migrations.AlterField(
            model_name='pkginfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monolith.PkgInfoCategory'),
        ),
        migrations.AlterField(
            model_name='pkginfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monolith.PkgInfoName'),
        ),
        migrations.AlterField(
            model_name='submanifest',
            name='meta_business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.MetaBusinessUnit'),
        ),
        migrations.AlterField(
            model_name='submanifestpkginfo',
            name='pkg_info_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monolith.PkgInfoName'),
        ),
    ]
