# Generated by Django 2.2.15 on 2020-10-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0038_auto_20190227_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledmachine',
            name='registered',
        ),
        migrations.RemoveField(
            model_name='enrolledmachine',
            name='registered_at',
        ),
        migrations.RemoveField(
            model_name='enrolledmachine',
            name='token',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='munki_release',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='taxonomies',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
