# Generated by Django 2.2.17 on 2020-11-29 18:33

from django.db import migrations


def set_default_manifest_names(apps, schema_editor):
    Manifest = apps.get_model("monolith", "Manifest")
    for manifest in Manifest.objects.select_related("meta_business_unit").all():
        manifest.name = manifest.meta_business_unit.name
        manifest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0041_auto_20201129_1756'),
    ]

    operations = [
        migrations.RunPython(set_default_manifest_names)
    ]
