# Generated by Django 2.2.17 on 2020-11-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0042_auto_20201129_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifest',
            options={'ordering': ('name', 'meta_business_unit__name')},
        ),
        migrations.AlterField(
            model_name='manifest',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
