# Generated by Django 2.2.20 on 2021-04-07 06:56

from django.db import migrations


def update_manifest_enrollment_packages(apps, schema_editor):
    ManifestEnrollmentPackage = apps.get_model("monolith", "ManifestEnrollmentPackage")
    for mep in ManifestEnrollmentPackage.objects.all():
        pkg_info = mep.pkg_info
        if pkg_info:
            update_for = mep.pkg_info.pop("update_for", None)
            if update_for:
                mep.pkg_info["requires"] = update_for
                mep.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0044_auto_20201130_0824'),
    ]

    operations = [
        migrations.RunPython(update_manifest_enrollment_packages),
    ]
