# Generated by Django 2.2.24 on 2022-01-11 15:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0045_auto_20210407_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='submanifestpkginfo',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
