# Generated by Django 3.2.12 on 2022-03-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0046_submanifestpkginfo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='scheme',
            field=models.CharField(
                choices=[('ipp', 'ipp'),
                         ('ipps', 'ipps'),
                         ('http', 'http'),
                         ('https', 'https'),
                         ('lpd', 'lpd'),
                         ('socket', 'socket')], default='ipp', max_length=6),
        ),
    ]
