# Generated by Django 3.2.12 on 2022-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0047_alter_printer_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestenrollmentpackage',
            name='pkg_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pkginfo',
            name='data',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='printer',
            name='pkg_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submanifestattachment',
            name='pkg_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='submanifestpkginfo',
            name='options',
            field=models.JSONField(default=dict),
        ),
    ]
