# Generated by Django 3.2.14 on 2023-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monolith", "0048_auto_20220329_0640"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submanifestattachment",
            name="key",
            field=models.CharField(
                choices=[
                    ("managed_installs", "Managed Installs"),
                    ("managed_uninstalls", "Managed Uninstalls"),
                    ("default_installs", "Default Installs"),
                    ("optional_installs", "Optional Installs"),
                    ("managed_updates", "Managed Updates"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="submanifestpkginfo",
            name="key",
            field=models.CharField(
                choices=[
                    ("managed_installs", "Managed Installs"),
                    ("managed_uninstalls", "Managed Uninstalls"),
                    ("default_installs", "Default Installs"),
                    ("optional_installs", "Optional Installs"),
                    ("managed_updates", "Managed Updates"),
                ],
                max_length=32,
            ),
        ),
    ]
