# Generated by Django 3.2.14 on 2023-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0049_auto_20230119_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifest',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
