# Generated by Django 3.2.14 on 2023-03-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0050_alter_manifest_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='manifestcatalog',
            unique_together={('manifest', 'catalog')},
        ),
    ]
