# Generated by Django 3.2.14 on 2023-03-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0051_alter_manifestcatalog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submanifestattachment',
            name='type',
            field=models.CharField(choices=[('package', 'package'), ('script', 'script')], max_length=32),
        ),
        migrations.DeleteModel(
            name='Printer',
        ),
        migrations.DeleteModel(
            name='PrinterPPD',
        ),
    ]
