# Generated by Django 3.2.14 on 2023-03-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0052_auto_20230315_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubManifestAttachment',
        ),
    ]
