# Generated by Django 4.2.13 on 2024-06-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0055_alter_catalog_options_alter_manifestcatalog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='provisioning_uid',
            field=models.CharField(editable=False, max_length=256, null=True, unique=True),
        ),
    ]
