# Generated by Django 4.2.18 on 2025-03-01 13:41

from django.db import migrations, models
import zentral.contrib.monolith.models
import zentral.utils.storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "monolith",
            "0057_alter_pkginfocategory_name_alter_repository_backend_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestenrollmentpackage",
            name="file",
            field=models.FileField(
                blank=True,
                storage=zentral.utils.storage.select_dist_storage,
                upload_to=zentral.contrib.monolith.models.enrollment_package_path,
            ),
        ),
        migrations.AlterField(
            model_name="pkginfo",
            name="file",
            field=models.FileField(
                blank=True,
                storage=zentral.utils.storage.select_dist_storage,
                upload_to=zentral.contrib.monolith.models.pkg_info_path,
            ),
        ),
    ]
