# Generated by Django 5.2.9 on 2025-12-16 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0058_alter_manifestenrollmentpackage_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manifestsubmanifest',
            options={'ordering': ('sub_manifest__name',)},
        ),
        migrations.AlterUniqueTogether(
            name='manifestsubmanifest',
            unique_together={('manifest', 'sub_manifest')},
        ),
    ]
