# Generated by Django 5.2.17 on 2026-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monolith', '0059_alter_manifestsubmanifest_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submanifestpkginfo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='submanifestpkginfo',
            constraint=models.UniqueConstraint(
                fields=('sub_manifest', 'pkg_info_name', 'key'),
                name='monolith_submanifestpkginfo_unique_pkg_info_name_key',
            ),
        ),
    ]
